From the followig data:
1. retrieve the total revenue of our shop in Berlin
2. retrieve the product that has brought the most money

In [133]:
coffee_shop = {
    "products": [
        {"id": 1, "name": "Espresso Beans 1kg", "price": 18.50, "stock": 12, "category": "coffee"},
        {"id": 2, "name": "French Press",       "price": 24.00, "stock": 5,  "category": "gear"},
        {"id": 3, "name": "Mug",                "price": 8.00,  "stock": 0,  "category": "gear"},
        {"id": 4, "name": "Filter Papers (100)", "price": 4.50, "stock": 40, "category": "consumable"},
        {"id": 5, "name": "Cold Brew Bottle",   "price": 14.90, "stock": 7,  "category": "gear"},
    ],
    "customers": [
        {"id": 101, "name": "Alice", "city": "Berlin"},
        {"id": 102, "name": "Ben",   "city": "Hamburg"},
        {"id": 103, "name": "Chloe", "city": "Berlin"},
        {"id": 104, "name": "Diego", "city": "Munich"},
    ],
    "orders": [
        {"order_id": "O1001", "customer_id": 101, "date": "2025-08-25",
         "items": [{"product_id": 1, "qty": 1}, {"product_id": 3, "qty": 2}]},
        {"order_id": "O1002", "customer_id": 102, "date": "2025-08-26",
         "items": [{"product_id": 2, "qty": 1}]},
        {"order_id": "O1003", "customer_id": 101, "date": "2025-08-26",
         "items": [{"product_id": 4, "qty": 5}]},
        {"order_id": "O1004", "customer_id": 103, "date": "2025-08-27",
         "items": [{"product_id": 1, "qty": 2}, {"product_id": 5, "qty": 1}]},
        {"order_id": "O1005", "customer_id": 104, "date": "2025-08-28",
         "items": [{"product_id": 3, "qty": 1}, {"product_id": 4, "qty": 2}]},
        {"order_id": "O1006", "customer_id": 103, "date": "2025-08-29",
         "items": [{"product_id": 2, "qty": 1}, {"product_id": 4, "qty": 1}]},
    ],
}

## Load dataframes

In [44]:
import pandas as pd

In [45]:
products = pd.DataFrame(coffee_shop["products"])
customers = pd.DataFrame(coffee_shop["customers"])
orders = pd.DataFrame(coffee_shop["orders"])

In [46]:
products

   id                 name  price  stock    category
0   1   Espresso Beans 1kg   18.5     12      coffee
1   2         French Press   24.0      5        gear
2   3                  Mug    8.0      0        gear
3   4  Filter Papers (100)    4.5     40  consumable
4   5     Cold Brew Bottle   14.9      7        gear

In [47]:
customers

    id   name     city
0  101  Alice   Berlin
1  102    Ben  Hamburg
2  103  Chloe   Berlin
3  104  Diego   Munich

In [48]:
orders

,order_id,customer_id,date,items
0,O1001,101,2025-08-25,"[{'product_id': 1, 'qty': 1}, {'product_id': 3..."
1,O1002,102,2025-08-26,"[{'product_id': 2, 'qty': 1}]"
2,O1003,101,2025-08-26,"[{'product_id': 4, 'qty': 5}]"
3,O1004,103,2025-08-27,"[{'product_id': 1, 'qty': 2}, {'product_id': 5..."
4,O1005,104,2025-08-28,"[{'product_id': 3, 'qty': 1}, {'product_id': 4..."
5,O1006,103,2025-08-29,"[{'product_id': 2, 'qty': 1}, {'product_id': 4..."

## Product that has brought the most money

In [100]:
product_ids = []
qtys = []
for lst in orders["items"]:
    for product in lst:
        order_index.append(ind)
        product_ids.append(product["product_id"])
        qtys.append(product["qty"])

In [101]:
order_index

[0, 0, 1, 2, 3, 3, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

In [102]:
product_ids

[1, 3, 2, 4, 1, 5, 3, 4, 2, 4]

In [103]:
amounts_sold = pd.DataFrame({
    "id": product_ids,
    "quantity": qtys
})

In [104]:
amounts_sold

   id  quantity
0   1         1
1   3         2
2   2         1
3   4         5
4   1         2
5   5         1
6   3         1
7   4         2
8   2         1
9   4         1

In [105]:
amounts_sold_per_product = amounts_sold.groupby("id").sum()
amounts_sold_per_product

    quantity
id
1          3
2          2
3          3
4          8
5          1

In [54]:
products = products.join(amounts_sold_per_product, on="id")

In [55]:
products["total_revenue"] = products["price"] * products["quantity"]

In [56]:
products

   id                 name  price  stock    category  quantity  total_revenue
0   1   Espresso Beans 1kg   18.5     12      coffee         3           55.5
1   2         French Press   24.0      5        gear         2           48.0
2   3                  Mug    8.0      0        gear         3           24.0
3   4  Filter Papers (100)    4.5     40  consumable         8           36.0
4   5     Cold Brew Bottle   14.9      7        gear         1           14.9

In [99]:
products[products["total_revenue"] == products["total_revenue"].max()]

   id                name  price  stock category  quantity  total_revenue
0   1  Espresso Beans 1kg   18.5     12   coffee         3           55.5

### Same without pandas

In [140]:
sold_prod_ids = []
sold_prod_qtys = []
for order in coffee_shop["orders"]:
    for item in (order["items"]):
        sold_prod_ids.append(item["product_id"])
        sold_prod_qtys.append(item["qty"])

In [152]:
prod_ids = []
prod_prices = []
prod_names = []
for product in coffee_shop["products"]:
    prod_ids.append(product["id"])
    prod_prices.append(product["price"])
    prod_names.append(product["name"])

In [146]:
sold_prod_total_prices = {}
for ind2, prod in enumerate(prod_ids):
    for ind1, sold_prod in enumerate(sold_prod_ids):
        if sold_prod == prod:
            total = sold_prod_qtys[ind1] * prod_prices[ind2]
            if prod not in sold_prod_total_prices:
                sold_prod_total_prices[prod] = total
            else:
                sold_prod_total_prices[prod] += total

In [154]:
most_sold_prod_id = max(sold_prod_total_prices, key=sold_prod_total_prices.get)

In [155]:
for ind, prod in enumerate(prod_ids):
    if prod == most_sold_prod_id:
        print(prod_names[ind])

Espresso Beans 1kg

## Total revenue of our shop in Berlin

In [68]:
exploded_orders = orders.explode("items")

In [22]:
berlin_customer_ids = customers[customers["city"] == "Berlin"]["id"]

In [69]:
berlin_orders = exploded_orders[exploded_orders["customer_id"].isin(berlin_customer_ids)]

In [70]:
berlin_orders

  order_id  customer_id        date                        items
0    O1001          101  2025-08-25  {'product_id': 1, 'qty': 1}
0    O1001          101  2025-08-25  {'product_id': 3, 'qty': 2}
2    O1003          101  2025-08-26  {'product_id': 4, 'qty': 5}
3    O1004          103  2025-08-27  {'product_id': 1, 'qty': 2}
3    O1004          103  2025-08-27  {'product_id': 5, 'qty': 1}
5    O1006          103  2025-08-29  {'product_id': 2, 'qty': 1}
5    O1006          103  2025-08-29  {'product_id': 4, 'qty': 1}

In [130]:
berlin_total = 0
for product in berlin_orders["items"]:
    product_price = float(products[products["id"] == product["product_id"]]["price"])
    total_product = product_price * product["qty"]
    berlin_total += total_product

/var/folders/3j/f7d6p9t136x34vdmdy30wrrc0000gn/T/ipykernel_6096/957401958.py:3: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  product_price = float(products[products["id"] == product["product_id"]]["price"])

In [131]:
berlin_total

137.4

### Same without pandas

In [ ]:
customers_berlin = []
for customer in coffee_shop["customers"]:
    if customer["city"] == "Berlin":
        customers_berlin.append(customer["id"])

In [ ]:
customers_berlin

[101, 103]

In [ ]:
product_ids = []
product_names = []
product_prices = []
for product in coffee_shop["products"]:
    product_ids.append(product["id"])
    product_names.append(product["name"])
    product_prices.append(product["price"])

In [ ]:
order_cust_ids = []
order_items = []
for order in coffee_shop["orders"]:
    order_cust_ids.append(order["customer_id"])
    order_items.append(order["items"])

In [ ]:
order_items_berlin = []
for ind, cust_id in enumerate(order_cust_ids):
    if cust_id in customers_berlin:
        order_items_berlin.append(order_items[ind])

In [ ]:
order_items_berlin_prod_ids = []
order_items_berlin_qty = []
for lst in order_items_berlin:
    for item in lst:
        order_items_berlin_prod_ids.append(item["product_id"])
        order_items_berlin_qty.append(item["qty"])

In [ ]:
order_items_berlin_total_prices = []
for ind1, prod in enumerate(order_items_berlin_prod_ids):
    for ind2, p_id in enumerate(product_ids):
        if prod == p_id:
            order_items_berlin_total_prices.append(product_prices[ind2] * order_items_berlin_qty[ind1])

In [ ]:
sum(order_items_berlin_total_prices)

137.4