# Web Scraping

![legtsgo](https://media.giphy.com/media/dwmNhd5H7YAz6/giphy.gif)

By the end of this lesson, you will be able to:

- Identify the primary components of web technologies and their roles: HTML, CSS, and JavaScript.
- Explain the hierarchical structure of HTML and the significance of tags, attributes, and their relationship.
- Utilize the **requests** and **Beautiful Soup** libraries to scrape data from a static web page.
- Construct and execute a script to scrape data from a webpage and export it into a structured text file using the pandas library.

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Web-Scraping" data-toc-modified-id="Web-Scraping-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Web Scraping</a></span><ul class="toc-item"><li><span><a href="#What-is-Web-Scraping" data-toc-modified-id="What-is-Web-Scraping-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>What is Web Scraping</a></span></li><li><span><a href="#Web-structure" data-toc-modified-id="Web-structure-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Web structure</a></span></li><li><span><a href="#HTML" data-toc-modified-id="HTML-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>HTML</a></span><ul class="toc-item"><li><span><a href="#Exploring-Web-Page-Structures" data-toc-modified-id="Exploring-Web-Page-Structures-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Exploring Web Page Structures</a></span></li><li><span><a href="#Fact-1:-HTML-is-Built-on-Tags" data-toc-modified-id="Fact-1:-HTML-is-Built-on-Tags-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>Fact 1: HTML is Built on Tags</a></span></li><li><span><a href="#Fact-2:-Tags-Can-Have-Attributes" data-toc-modified-id="Fact-2:-Tags-Can-Have-Attributes-1.3.3"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>Fact 2: Tags Can Have Attributes</a></span></li><li><span><a href="#Fact-3:-Tags-Can-Be-Nested" data-toc-modified-id="Fact-3:-Tags-Can-Be-Nested-1.3.4"><span class="toc-item-num">1.3.4&nbsp;&nbsp;</span>Fact 3: Tags Can Be Nested</a></span></li><li><span><a href="#Selecting-Specific-Elements-in-Web-Scraping" data-toc-modified-id="Selecting-Specific-Elements-in-Web-Scraping-1.3.5"><span class="toc-item-num">1.3.5&nbsp;&nbsp;</span>Selecting Specific Elements in Web Scraping</a></span></li></ul></li><li><span><a href="#Web-Scraping-with-Python" data-toc-modified-id="Web-Scraping-with-Python-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Web Scraping with Python</a></span><ul class="toc-item"><li><span><a href="#Requests:-Fetching-a-Web-Page" data-toc-modified-id="Requests:-Fetching-a-Web-Page-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>Requests: Fetching a Web Page</a></span></li><li><span><a href="#Parsing-HTML-with-Beautiful-Soup" data-toc-modified-id="Parsing-HTML-with-Beautiful-Soup-1.4.2"><span class="toc-item-num">1.4.2&nbsp;&nbsp;</span>Parsing HTML with Beautiful Soup</a></span><ul class="toc-item"><li><span><a href="#Extracting-Data" data-toc-modified-id="Extracting-Data-1.4.2.1"><span class="toc-item-num">1.4.2.1&nbsp;&nbsp;</span>Extracting Data</a></span></li><li><span><a href="#More-filtering-options" data-toc-modified-id="More-filtering-options-1.4.2.2"><span class="toc-item-num">1.4.2.2&nbsp;&nbsp;</span>More filtering options</a></span></li><li><span><a href="#Creating-a-DataFrame-with-the-data" data-toc-modified-id="Creating-a-DataFrame-with-the-data-1.4.2.3"><span class="toc-item-num">1.4.2.3&nbsp;&nbsp;</span>Creating a DataFrame with the data</a></span></li><li><span><a href="#💡-Check-for-understanding" data-toc-modified-id="💡-Check-for-understanding-1.4.2.4"><span class="toc-item-num">1.4.2.4&nbsp;&nbsp;</span>💡 Check for understanding</a></span></li><li><span><a href="#Scraping-many-pages" data-toc-modified-id="Scraping-many-pages-1.4.2.5"><span class="toc-item-num">1.4.2.5&nbsp;&nbsp;</span>Scraping many pages</a></span></li><li><span><a href="#CSS-selectors" data-toc-modified-id="CSS-selectors-1.4.2.6"><span class="toc-item-num">1.4.2.6&nbsp;&nbsp;</span>CSS selectors</a></span></li></ul></li><li><span><a href="#More-examples" data-toc-modified-id="More-examples-1.4.3"><span class="toc-item-num">1.4.3&nbsp;&nbsp;</span>More examples</a></span><ul class="toc-item"><li><span><a href="#BBC" data-toc-modified-id="BBC-1.4.3.1"><span class="toc-item-num">1.4.3.1&nbsp;&nbsp;</span>BBC</a></span></li></ul></li></ul></li><li><span><a href="#Comments" data-toc-modified-id="Comments-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Comments</a></span></li><li><span><a href="#Summary" data-toc-modified-id="Summary-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Summary</a></span></li><li><span><a href="#Further-materials" data-toc-modified-id="Further-materials-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Further materials</a></span><ul class="toc-item"><li><span><a href="#How-to-Solve-a-403-Error" data-toc-modified-id="How-to-Solve-a-403-Error-1.7.1"><span class="toc-item-num">1.7.1&nbsp;&nbsp;</span>How to Solve a 403 Error</a></span></li></ul></li></ul></li></ul></div>

## What is Web Scraping

Web scraping is a method employed by data analysts and developers to retrieve information from web pages. It involves fetching a web page and then parsing that page to obtain desired information. This technique is especially useful when the desired data isn't available through APIs. The extracted data can then be cleaned, analyzed, or stored in databases for further data analytics tasks.

## Web structure

The fundamental web technologies that form the structure of the websites we aim to scrape are:

- **HTML**: Standing as the backbone of almost all websites, HTML, the core markup language, is instrumental in creating web pages. It houses all the content available on a webpage.
  
- **CSS**: This stylesheet language works alongside HTML, taking charge of the presentation aspect of the webpages. It controls how HTML elements are displayed, setting the stage for a visually pleasing and organized web interface.

- **JavaScript**: Adding a dynamic touch to the websites, JavaScript comes into play to create interactive and animated content. This programming language has the power to alter webpage content even after it has loaded, bringing a dynamic and responsive element to web designs.

In this lesson, we will work with the HTML from the websites.

## HTML

In the realm of web scraping, understanding HTML (Hypertext Markup Language) is crucial.

HTML is the standard markup language used to create web pages. Think of it as the skeleton or blueprint of a website. It structures content on the web, defining elements like paragraphs, headings, links, lists, and images. These elements are represented by "tags", which enclose content to give it meaning and context.

When web scraping, you'll often navigate through this HTML structure to pinpoint and extract the exact data you need. Tools like web browsers' "Inspect" or "View Source" features allow you to see the underlying HTML of a page, which is invaluable when determining how to access specific pieces of content programmatically.

![](https://github.com/data-bootcamp-v4/lessons/blob/main/img/html.png?raw=true)

### Exploring Web Page Structures

To inspect the underlying HTML of a web page, right-click anywhere on the page. Choose "View Page Source" in browsers like Chrome or Firefox. For Internet Explorer, choose "View Source," and for Safari, select "Show Page Source." (In Safari, if this option isn't visible, navigate to Safari Preferences, click on the Advanced tab, and enable "Show Develop menu in menu bar.")

To embark on your web scraping journey, you just need to grasp **three foundational aspects** of HTML.

### Fact 1: HTML is Built on Tags

At its core, HTML is composed of content enveloped in `<tags>`. It typically houses the textual content we aim to scrape, highlighted by these "tags" enclosed by angle brackets. These tags give structure and meaning, instructing the browser on how to present the content. The acronym "HTML" stands for Hyper Text Markup Language.

HTML follows a tree-like structure, encompassing parent tags, child tags, and sibling tags:
```
<html>
    <head>
        <title>Page Title</title>
    </head>
    <body>
        <h1>My First Heading</h1>
        <p>My first paragraph.</p>
    </body>
</html>
```

For instance, consider the `<strong>` tag, signaling bold formatting. If "Jan. 21" is encapsulated between an opening `<strong>` tag and its corresponding closing `</strong>` tag, it denotes where the bold styling begins and ends. This pair of tags instructs the browser to render the enclosed text, "Jan. 21", in bold.

Tags come in various types, each suited to encapsulate specific content:
 * **Headings**: `<h1>`, `<h2>`, `<h3>`, `<h4>`...
 * **Phrasing**: `<b>`, `<strong>`, `<sub>`, `<i>`, `<a>`...
 * **Embedded Content**: `<audio>`, `<img>`, `<video>`, `<iframe>`...
 * **Tabulated Data**: `<table>`, `<tr>`, `<td>`, `<tbody>`...
 * **Page Sections**: `<header>`, `<section>`, `<nav>`, `<article>`...
 * **Metadata and Scripts**: `<meta>`, `<title>`, `<script>`, `<link>`...

#### BeautifulSoup Example

In [1]:
html_doc = """<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>

<p class="story">Once upon a time there were three little sisters; and their names were
<a href="http://example.com/elsie" class="sister" id="link1">Elsie</a>,
<a href="http://example.com/lacie" class="sister" id="link2">Lacie</a> and
<a href="http://example.com/tillie" class="sister" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>

<p class="story">...</p>
"""

In [2]:
from bs4 import BeautifulSoup

In [4]:
soup = BeautifulSoup(html_doc)

In [10]:
print(soup.prettify())

<html>
 <head>
  <title>
   The Dormouse's story
  </title>
 </head>
 <body>
  <p class="title">
   <b>
    The Dormouse's story
   </b>
  </p>
  <p class="story">
   Once upon a time there were three little sisters; and their names were
   <a class="sister" href="http://example.com/elsie" id="link1">
    Elsie
   </a>
   ,
   <a class="sister" href="http://example.com/lacie" id="link2">
    Lacie
   </a>
   and
   <a class="sister" href="http://example.com/tillie" id="link3">
    Tillie
   </a>
   ;
and they lived at the bottom of a well.
  </p>
  <p class="story">
   ...
  </p>
 </body>
</html>

In [21]:
soup.find("title")

In [22]:
soup.find("title").text

"The Dormouse's story"

In [23]:
soup.find("title").get_text()

"The Dormouse's story"

In [27]:
soup.find("body")

<body>
<p class="title"><b>The Dormouse's story</b></p>
<p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>
<p class="story">...</p>
</body>

In [34]:
soup.find("p") # only returns the first element of that tag

In [41]:
soup.find_all("p")

[<p class="title"><b>The Dormouse's story</b></p>,
 <p class="story">Once upon a time there were three little sisters; and their names were
 <a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
 <a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
 <a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
 and they lived at the bottom of a well.</p>,
 <p class="story">...</p>]

In [42]:
soup.find_all("p")[1]

<p class="story">Once upon a time there were three little sisters; and their names were
<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
<a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
<a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>

In [46]:
soup.find_all("p")[1].get_text()

'Once upon a time there were three little sisters; and their names were\nElsie,\nLacie and\nTillie;\nand they lived at the bottom of a well.'

In [44]:
print(soup.find_all("p")[1].get_text())

Once upon a time there were three little sisters; and their names were
Elsie,
Lacie and
Tillie;
and they lived at the bottom of a well.

In [45]:
# Retrieve the name of the 3rd sister
soup.find_all("a")[2].get_text()

'Tillie'

### Fact 2: Tags Can Have Attributes

HTML tags can possess "attributes," which are defined within the opening tag itself.

Examine the following examples:

- `<span class="short-desc">`: Here, the `<span>` tag has a `class` attribute with the value "short-desc".
- `<div> Zapas Marca Joma X54 </div>`: This tag doesn't contain any attributes.
- `<div class="price-item" id="offer"> Zapas Marca Joma X54 </div>`: The `div` tag here has two attributes - `class` with the value "price-item" and `id` with the value "offer".
- `<a class="text-monospace" id="name_132" href="http://www.example.com"> Page Content </a>
`: This `a` tag encompasses the following attributes:
    + `class`: With the value "text-monospace". Remember, the class isn't unique across the page.
    + `id`: With the value "name_132". IDs are meant to be unique identifiers for tags on the page.
    + `href`: With the value www.example.com. The href commonly represents a link to another section of the page or to an external website.

**Key Notes**:
- The `id` attribute should be unique for a tag; no two tags should share the same `id`.
- The `class` attribute isn't meant to be unique. Instead, it often groups tags exhibiting similar behavior or styles.

For web scraping purposes, **understanding the semantics** behind terms like `<span>`, `class`, or `short-desc` **isn't crucial**. The key takeaway is recognizing that tags can possess attributes and understanding their structural representation. When extracting content, our goal is to pinpoint the right tags within a webpage's HTML.

**Other commonly used attributes in HTML**

Several attributes in HTML provide additional information or modify elements. Some of these frequently used attributes include:

 * **`dir`**: Determines the text direction within an element, allowing for either forward or backward writing.
 * **`lang`**: Designates the language of the content within an element.
 * **`style`**: Applies inline styling to an element (Note: This shouldn't be mixed up with the `<style>` tag).
 * **`title`**: Offers supplementary details about an element, often displayed as a tooltip (Important: This is distinct from the `<title>` tag).

...and many more.

#### BeautifulSoup Example

In [53]:
soup.find_all("a", id = "link3")

In [50]:
soup.find_all("a", id = "link3")[0].get_text()

'Tillie'

In [60]:
soup.find_all("p", class_ = "title")

In [59]:
# Retrieve all the paragraphs with class "title"
soup.find_all("p", {"class": "title"})


### Fact 3: Tags Can Be Nested

Imagine the following segment of HTML code:

`Hello <strong><em>Ironhack</em> students</strong>`

Here, the phrase **Ironhack students** would be displayed in bold since it resides between the `<strong>` and `</strong>` tags. Additionally, the word ***Ironhack*** would be italicized due to the `<em>` tag, which signifies italic formatting. However, the word "Hello" remains unaffected by any formatting, as it lies outside both the `<strong>` and `<em>` tags. This results in the display:

Hello ***Ironhack* students**

This example illustrates a key principle: **tags influence the text from their opening to their closing points,** even if they are nested within other tags.

### Selecting Specific Elements in Web Scraping

When diving into web scraping, it's essential to target specific elements efficiently. To hone in on the precise content you need, consider filtering tags based on:

 * **Tag Name**: The main type of the element (e.g., `<div>`, `<a>`, `<p>`).
 * **Class**: A descriptor that groups multiple elements with similar characteristics.
 * **ID**: A unique identifier assigned to a particular element.
 * **Other Attributes**: Additional properties like `href`, `title`, or `lang` that can further specify the elements of interest.

## Web Scraping with Python

In this lesson, we'll use the `requests` library to fetch web pages and `Beautiful Soup` from the `bs4` package to parse these pages and extract information.

Ensure you've installed the required packages:

In [ ]:
#!pip install requests beautifulsoup4

### Requests: Fetching a Web Page

First, we use the `requests` library to fetch the content of a webpage.

In [72]:
import requests

url = "https://www.gutenberg.org/ebooks/search/?sort_order=downloads"
response = requests.get(url)
response

In [73]:
# response 200 means the request was successful (as anything starting with 2)

The provided code retrieves the webpage content from the given URL and saves it in a `response` object. This object possesses either a `text` or `content` attribute, holding the HTML code similar to what we observe when inspecting the source in a web browser.

In [74]:
response.content

b'<!DOCTYPE html>\n<!--\n\nDON\'T USE THIS PAGE FOR SCRAPING.\n\nSeriously. You\'ll only get your IP blocked.\n\nDownload https://www.gutenberg.org/feeds/catalog.rdf.bz2 instead,\nwhich contains *all* Project Gutenberg metadata in one RDF/XML file.\n\n--><html lang="en">\n\n\n\n\n<head>\n<style>\n.icon   { background: transparent url(/pics/sprite.png) 0 0 no-repeat; }\n.page_content a.subtle_link:link {color:currentColor; text-decoration: none;}\n.page_content a.subtle_link:hover {color:#003366}\n</style>\n<link rel="stylesheet" type="text/css" href="/gutenberg/pg-desktop-one.css?v=1.1">\n<link rel="stylesheet" type="text/css" href="/gutenberg/style2.css?v=1.7">\n<link rel="stylesheet" type="text/css" href="/gutenberg/new_nav.css?v=1.6">\n<link rel="stylesheet" type="text/css" href="/gutenberg/search_options.css?v=1">\n<script>//\nvar canonical_url   = "http://www.gutenberg.org/ebooks/search/?sort_order=downloads";\nvar lang            = "en";\nvar msg_load_more   = "Load More Results\xe2\x80\xa6";\nvar page_mode       = "screen";\nvar dialog_title    = "";\nvar dialog_message  = "";\n//</script>\n<script src="/js/pg-two.js"></script>\n<link rel="shortcut icon" href="/gutenberg/favicon.ico">\n<link rel="canonical" href="http://www.gutenberg.org/ebooks/search/?sort_order=downloads">\n<link rel="search" type="application/opensearchdescription+xml" title="Search Project Gutenberg" href="https://www.gutenberg.org/catalog/osd-books.xml">\n<link rel="alternate nofollow" type="application/atom+xml;profile=opds-catalog" title="OPDS feed" href="/ebooks/search.opds/?sort_order=downloads">\n<link rel="apple-touch-icon" href="/gutenberg/apple-icon.png">\n<meta name="viewport" content="width=device-width">\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\n<meta http-equiv="default-style" content="text/css">\n<meta name="title" content="All Books (sorted by popularity)">\n<meta name="description" content="Project Gutenberg offers 76,609 free eBooks for Kindle, iPad, Nook, Android, and iPhone.">\n<meta name="keywords" content="ebook, ebooks, free ebooks, free books, book, books, audio books">\n<meta name="classification" content="public">\n<meta property="og:title" content="All Books (sorted by popularity)">\n<meta property="og:description" content="Project Gutenberg offers 76,609 free eBooks for Kindle, iPad, Nook, Android, and iPhone.">\n<meta property="og:type" content="website">\n<meta property="og:image" content="http://www.gutenberg.org/pics/logo-144x144.png">\n<meta property="og:url" content="http://www.gutenberg.org/ebooks/search/?sort_order=downloads">\n<meta property="og:site_name" content="Project Gutenberg">\n<meta property="fb:app_id" content="115319388529183">\n<meta name="twitter:card" content="summary">\n<meta name="twitter:site" content="@gutenberg_new">\n<meta name="twitter:image" content="http://www.gutenberg.org/pics/logo-144x144.png">\n<meta name="twitter:image:alt" content="book cover image">\n<title>All Books (sorted by popularity) - Project Gutenberg</title>\n<link rel="self" title="This Page" href="/ebooks/search/">\n<link rel="next" title="Next Page" href="/ebooks/search/?start_index=26">\n<meta name="totalResults" content="26">\n<meta name="startIndex" content="1">\n<meta name="itemsPerPage" content="25">\n</head>\n<body class="search_results_page">\n<header class="noprint">\n<input type="radio" name="toggle" id="search-toggle" style="display: none">\n<input type="radio" name="toggle" id="search-close" style="display: none">\n<input type="checkbox" id="about-toggle" style="display: none">\n<div class="logo-container">\n<a href="#content" class="visually-hidden focusable skip-link">\nSkip to main content\n</a>\n<a id="main_logo" href="/" class="no-hover">\n<img src="/gutenberg/pg-logo-129x80.png" alt="Project Gutenberg" draggable="false">\n</a>\n</div>\n<div class="top-header">\n<form class="search-form" method="get" action="/ebooks/search/" accept-charset="utf-8">\n<label for="search-toggle" class="search-icon-btn" aria-label="Open Search">\n<svg class="search-icon" viewBox="0 0 24 24" fill="currentColor" width="1em" height="1em">\n<path d="M15.5 14h-.79l-.28-.27a6.5 6.5 0 0 0 1.48-5.34c-.47-2.78-2.79-5-5.59-5.34a6.505 6.505 0 0 0-7.27 7.27c.34 2.8 2.56 5.12 5.34 5.59a6.5 6.5 0 0 0 5.34-1.48l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>\n<path d="M0 0h24v24H0z" fill="none"></path>\n</svg>\n</label>\n<label for="search-close" class="search-close-btn" aria-label="Close Search">X</label>\n<input type="text" class="search-input" name="query" placeholder="Quick search" aria-label="Search books">\n<button type="submit" class="search-button">Go!</button>\n</form>\n<div class="donate-container">\n<form class="donatelink" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="new">\n<input type="hidden" name="cmd" value="_s-xclick">\n<input type="hidden" name="hosted_button_id" value="XKAL6BZL3YPSN">\n<input class="donbtn" type="image" src="/pics/en_US.gif" name="submit" alt="Donate via PayPal">\n</form>\n<a href="/donate/" class="donate-link"> Donate </a>\n</div>\n</div>\n<label for="about-toggle" class="dropdown-overlay"></label>\n<div class="lower-header">\n<div class="dropdown" tabindex="0">\n<label for="about-toggle" class="dropdown-button" aria-haspopup="true">About<span aria-hidden="true" class="dropdown-icon">\xe2\x96\xbc</span></label>\n<div class="dropdown-content">\n<a href="/about/">About Project Gutenberg </a>\n<a href="/about/contact_information.html">Contact Us</a>\n<a href="/about/background/">History &amp; Philosophy</a>\n<a href="/help/mobile.html">Kindle &amp; eReaders</a>\n<a href="/help/">Help Pages</a>\n<a href="/ebooks/offline_catalogs.html">Offline Catalogs</a>\n<a href="/donate/">Donate</a>\n</div>\n</div>\n<div class="main-links">\n<a href="/browse/scores/top" class="link-freq-downloaded">Frequently Downloaded</a>\n<a href="/ebooks/categories" class="link-main-categories">Main Categories</a>\n<a href="/ebooks/bookshelf/" class="link-reading-lists">Reading Lists</a>\n<a href="/ebooks/" class="link-advanced-search">Search Options</a>\n</div>\n</div>\n<div class="tertiary-header">\n<a href="/browse/scores/top" class="tertiary-link link-freq-downloaded">Frequently Downloaded</a>\n<a href="/ebooks/categories" class="tertiary-link link-main-categories">Main Categories</a>\n</div>\n</header>\n<div class="container">\n<div id="content" class="page_content">\n<h1><span class="icon icon_search"></span>All Books (sorted by popularity)</h1>\n<div class="body">\n<div>\n<ul class="results">\n<li class="grayed navlink">\n<a class="link" href="/ebooks/search/?sort_order=title" accesskey="0">\n<span class="cell leftcell without-cover">\n<span class="icon-wrapper">\n<span class="icon icon_alpha"></span>\n</span>\n</span>\n<span class="cell content">\n<span class="title">Sort Alphabetically by Title</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="grayed navlink">\n<a class="link" href="/ebooks/search/?sort_order=release_date" accesskey="1">\n<span class="cell leftcell without-cover">\n<span class="icon-wrapper">\n<span class="icon icon_date"></span>\n</span>\n</span>\n<span class="cell content">\n<span class="title">Sort by Release Date</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="statusline">\n<div class="padded">\n<span>Displaying results 1\xe2\x80\x9325</span>\n<span class="links">\n|\n<a title="Go to the next page of results." accesskey="+" href="/ebooks/search/?sort_order=downloads&amp;start_index=26">Next</a>\n</span>\n</div>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/2701" accesskey="3">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/2701/pg2701.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">Moby Dick; Or, The Whale</span>\n<span class="subtitle">Herman Melville</span>\n<span class="extra">109357 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/1513" accesskey="4">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/1513/pg1513.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">Romeo and Juliet</span>\n<span class="subtitle">William Shakespeare</span>\n<span class="extra">79901 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/84" accesskey="5">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/84/pg84.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">Frankenstein; Or, The Modern Prometheus</span>\n<span class="subtitle">Mary Wollstonecraft Shelley</span>\n<span class="extra">78777 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/2641" accesskey="6">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/2641/pg2641.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">A Room with a View</span>\n<span class="subtitle">E. M. Forster</span>\n<span class="extra">63493 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/100" accesskey="7">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/100/pg100.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">The Complete Works of William Shakespeare</span>\n<span class="subtitle">William Shakespeare</span>\n<span class="extra">59579 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/1342" accesskey="8">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/1342/pg1342.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">Pride and Prejudice</span>\n<span class="subtitle">Jane Austen</span>\n<span class="extra">59398 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/145" accesskey="9">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/145/pg145.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">Middlemarch</span>\n<span class="subtitle">George Eliot</span>\n<span class="extra">56093 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/37106" accesskey="0">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/37106/pg37106.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">Little Women; Or, Meg, Jo, Beth, and Amy</span>\n<span class="subtitle">Louisa May Alcott</span>\n<span class="extra">54766 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/16389" accesskey="1">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/16389/pg16389.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">The Enchanted April</span>\n<span class="subtitle">Elizabeth Von Arnim</span>\n<span class="extra">49749 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/67979" accesskey="2">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/67979/pg67979.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">The Blue Castle: a novel</span>\n<span class="subtitle">L. M. Montgomery</span>\n<span class="extra">48034 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/11" accesskey="3">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/11/pg11.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">Alice\'s Adventures in Wonderland</span>\n<span class="subtitle">Lewis Carroll</span>\n<span class="extra">46226 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/394" accesskey="4">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/394/pg394.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">Cranford</span>\n<span class="subtitle">Elizabeth Cleghorn Gaskell</span>\n<span class="extra">44579 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/6761" accesskey="5">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/6761/pg6761.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">The Adventures of Ferdinand Count Fathom \xe2\x80\x94 Complete</span>\n<span class="subtitle">T. Smollett</span>\n<span class="extra">43828 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/2160" accesskey="6">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/2160/pg2160.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">The Expedition of Humphry Clinker</span>\n<span class="subtitle">T. Smollett</span>\n<span class="extra">43817 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/6593" accesskey="7">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/6593/pg6593.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">History of Tom Jones, a Foundling</span>\n<span class="subtitle">Henry Fielding</span>\n<span class="extra">42670 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/4085" accesskey="8">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/4085/pg4085.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">The Adventures of Roderick Random</span>\n<span class="subtitle">T. Smollett</span>\n<span class="extra">42295 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/1259" accesskey="9">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/1259/pg1259.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">Twenty years after</span>\n<span class="subtitle">Alexandre Dumas and Auguste Maquet</span>\n<span class="extra">41825 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/5197" accesskey="0">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/5197/pg5197.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">My Life \xe2\x80\x94 Volume 1</span>\n<span class="subtitle">Richard Wagner</span>\n<span class="extra">41224 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/33944" accesskey="1">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/33944/pg33944.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">How to Observe: Morals and Manners</span>\n<span class="subtitle">Harriet Martineau</span>\n<span class="extra">39414 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/345" accesskey="2">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/345/pg345.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">Dracula</span>\n<span class="subtitle">Bram Stoker</span>\n<span class="extra">38150 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/2554" accesskey="3">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/2554/pg2554.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">Crime and Punishment</span>\n<span class="subtitle">Fyodor Dostoyevsky</span>\n<span class="extra">32404 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/52621" accesskey="4">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/52621/pg52621.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">Society in America, Volume 1 (of 2)</span>\n<span class="subtitle">Harriet Martineau</span>\n<span class="extra">29488 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/43" accesskey="5">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/43/pg43.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">The Strange Case of Dr. Jekyll and Mr. Hyde</span>\n<span class="subtitle">Robert Louis Stevenson</span>\n<span class="extra">29426 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/174" accesskey="6">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/174/pg174.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">The Picture of Dorian Gray</span>\n<span class="subtitle">Oscar Wilde</span>\n<span class="extra">28774 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="booklink">\n<a class="link" href="/ebooks/16328" accesskey="7">\n<span class="cell leftcell with-cover">\n<img class="cover-thumb" src="/cache/epub/16328/pg16328.cover.small.jpg" alt="">\n</span>\n<span class="cell content">\n<span class="title">Beowulf: An Anglo-Saxon Epic Poem</span>\n<span class="extra">28489 downloads</span>\n</span>\n<span class="hstrut"></span>\n</a>\n</li>\n<li class="statusline">\n<div class="padded">\nDisplaying results 1\xe2\x80\x9325\n<span class="links">\n|\n<a title="Go to the next page of results." accesskey="+" href="/ebooks/search/?sort_order=downloads&amp;start_index=26">Next</a>\n</span>\n</div>\n</li>\n</ul>\n</div>\n</div>\n</div>\n</div>\n<div class="footer">\n<footer>\n<ul>\n<li>\n<a href="/about/" title="About Project Gutenberg">About Project Gutenberg</a>\n</li>\n<li>\n<a href="/policy/privacy_policy.html" title="Privacy Policy">Privacy policy</a>\n</li>\n<li>\n<a href="/policy/permission.html" title="Permissions, Licensing and other Common Requests">Permissions</a>\n</li>\n<li>\n<a href="/policy/terms_of_use.html" title="Terms of Use">Terms of Use</a>\n</li>\n<li>\n<a href="/about/contact_information.html" title="How to contact Project Gutenberg">Contact Us</a>\n</li>\n<li><a href="/help/" title="Help, How-To, Procedures, Guidance and Information">Help</a></li>\n</ul>\n<a href="https://www.ibiblio.org/" title="Project Gutenberg is hosted by ibiblio">\n<img src="/gutenberg/ibiblio-logo.png" alt="ibiblio" width="110" height="32">\n</a>\n</footer>\n</div>\n</body>\n</html>'

In [75]:
response.headers # Response headers (as a Python dictionary)

{'date': 'Mon, 01 Sep 2025 09:53:39 GMT', 'server': 'CherryPy/18.10.0', 'content-type': 'text/html;charset=utf-8', 'content-language': 'en', 'pragma': 'no-cache', 'cache-control': 'no-cache, must-revalidate', 'expires': 'Sun, 28 Jan 2007 00:00:00 GMT', 'vary': 'Accept-Encoding', 'content-encoding': 'gzip', 'content-length': '4298', 'set-cookie': 'session_id=5c3c2ea3145de2f779603c7e365d207809d6e402; Domain=.gutenberg.org; expires=Mon, 01 Sep 2025 10:23:39 GMT; Max-Age=1800; Path=/', 'x-backend': 'gutenweb5'}

In [76]:
print(response.headers['Content-Type'])

text/html;charset=utf-8

When interacting with APIs, we typically receive data in JSON format. However, web scraping provides us with HTML, which can be challenging to navigate. Fortunately, Beautiful Soup simplifies this process, making our work more manageable!

### Parsing HTML with Beautiful Soup

To parse the HTML, we'll employ the renowned Python library, [Beautiful Soup 4](https://www.crummy.com/software/BeautifulSoup/bs4/doc/). For a deeper understanding of its functionalities, explore the [official documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/).

In [77]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.content, "html.parser")

The code above parses the HTML (stored in `response.content`) into a special object called `soup` that the Beautiful Soup library understands. In other words, Beautiful Soup is **reading the HTML and making sense of its structure.**

In [78]:
type(soup)

bs4.BeautifulSoup

In [79]:
print(soup.prettify())  # This formats the HTML in a readable way

<!DOCTYPE html>
<!--

DON'T USE THIS PAGE FOR SCRAPING.

Seriously. You'll only get your IP blocked.

Download https://www.gutenberg.org/feeds/catalog.rdf.bz2 instead,
which contains *all* Project Gutenberg metadata in one RDF/XML file.

-->
<html lang="en">
 <head>
  <style>
   .icon   { background: transparent url(/pics/sprite.png) 0 0 no-repeat; }
.page_content a.subtle_link:link {color:currentColor; text-decoration: none;}
.page_content a.subtle_link:hover {color:#003366}
  </style>
  <link href="/gutenberg/pg-desktop-one.css?v=1.1" rel="stylesheet" type="text/css"/>
  <link href="/gutenberg/style2.css?v=1.7" rel="stylesheet" type="text/css"/>
  <link href="/gutenberg/new_nav.css?v=1.6" rel="stylesheet" type="text/css"/>
  <link href="/gutenberg/search_options.css?v=1" rel="stylesheet" type="text/css"/>
  <script>
   //
var canonical_url   = "http://www.gutenberg.org/ebooks/search/?sort_order=downloads";
var lang            = "en";
var msg_load_more   = "Load More Results…";
var page_mode       = "screen";
var dialog_title    = "";
var dialog_message  = "";
//
  </script>
  <script src="/js/pg-two.js">
  </script>
  <link href="/gutenberg/favicon.ico" rel="shortcut icon"/>
  <link href="http://www.gutenberg.org/ebooks/search/?sort_order=downloads" rel="canonical"/>
  <link href="https://www.gutenberg.org/catalog/osd-books.xml" rel="search" title="Search Project Gutenberg" type="application/opensearchdescription+xml"/>
  <link href="/ebooks/search.opds/?sort_order=downloads" rel="alternate nofollow" title="OPDS feed" type="application/atom+xml;profile=opds-catalog"/>
  <link href="/gutenberg/apple-icon.png" rel="apple-touch-icon"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <meta content="text/css" http-equiv="default-style"/>
  <meta content="All Books (sorted by popularity)" name="title"/>
  <meta content="Project Gutenberg offers 76,609 free eBooks for Kindle, iPad, Nook, Android, and iPhone." name="description"/>
  <meta content="ebook, ebooks, free ebooks, free books, book, books, audio books" name="keywords"/>
  <meta content="public" name="classification"/>
  <meta content="All Books (sorted by popularity)" property="og:title"/>
  <meta content="Project Gutenberg offers 76,609 free eBooks for Kindle, iPad, Nook, Android, and iPhone." property="og:description"/>
  <meta content="website" property="og:type"/>
  <meta content="http://www.gutenberg.org/pics/logo-144x144.png" property="og:image"/>
  <meta content="http://www.gutenberg.org/ebooks/search/?sort_order=downloads" property="og:url"/>
  <meta content="Project Gutenberg" property="og:site_name"/>
  <meta content="115319388529183" property="fb:app_id"/>
  <meta content="summary" name="twitter:card"/>
  <meta content="@gutenberg_new" name="twitter:site"/>
  <meta content="http://www.gutenberg.org/pics/logo-144x144.png" name="twitter:image"/>
  <meta content="book cover image" name="twitter:image:alt"/>
  <title>
   All Books (sorted by popularity) - Project Gutenberg
  </title>
  <link href="/ebooks/search/" rel="self" title="This Page"/>
  <link href="/ebooks/search/?start_index=26" rel="next" title="Next Page"/>
  <meta content="26" name="totalResults"/>
  <meta content="1" name="startIndex"/>
  <meta content="25" name="itemsPerPage"/>
 </head>
 <body class="search_results_page">
  <header class="noprint">
   <input id="search-toggle" name="toggle" style="display: none" type="radio"/>
   <input id="search-close" name="toggle" style="display: none" type="radio"/>
   <input id="about-toggle" style="display: none" type="checkbox"/>
   <div class="logo-container">
    <a class="visually-hidden focusable skip-link" href="#content">
     Skip to main content
    </a>
    <a class="no-hover" href="/" id="main_logo">
     <img alt="Project Gutenberg" draggable="false" src="/gutenberg/pg-logo-129x80.png"/>
    </a>
   </div>
   <div class="top-header">
    <form accept-charset="utf-8" action="/ebooks/search/" class="search-form" method="get">
     <label aria-label="Open Search" class="search-icon-btn" for="search-toggle">
      <svg class="search-icon" fill="currentColor" height="1em" viewbox="0 0 24 24" width="1em">
       <path d="M15.5 14h-.79l-.28-.27a6.5 6.5 0 0 0 1.48-5.34c-.47-2.78-2.79-5-5.59-5.34a6.505 6.505 0 0 0-7.27 7.27c.34 2.8 2.56 5.12 5.34 5.59a6.5 6.5 0 0 0 5.34-1.48l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z">
       </path>
       <path d="M0 0h24v24H0z" fill="none">
       </path>
      </svg>
     </label>
     <label aria-label="Close Search" class="search-close-btn" for="search-close">
      X
     </label>
     <input aria-label="Search books" class="search-input" name="query" placeholder="Quick search" type="text"/>
     <button class="search-button" type="submit">
      Go!
     </button>
    </form>
    <div class="donate-container">
     <form action="https://www.paypal.com/cgi-bin/webscr" class="donatelink" method="post" target="new">
      <input name="cmd" type="hidden" value="_s-xclick"/>
      <input name="hosted_button_id" type="hidden" value="XKAL6BZL3YPSN"/>
      <input alt="Donate via PayPal" class="donbtn" name="submit" src="/pics/en_US.gif" type="image"/>
     </form>
     <a class="donate-link" href="/donate/">
      Donate
     </a>
    </div>
   </div>
   <label class="dropdown-overlay" for="about-toggle">
   </label>
   <div class="lower-header">
    <div class="dropdown" tabindex="0">
     <label aria-haspopup="true" class="dropdown-button" for="about-toggle">
      About
      <span aria-hidden="true" class="dropdown-icon">
       ▼
      </span>
     </label>
     <div class="dropdown-content">
      <a href="/about/">
       About Project Gutenberg
      </a>
      <a href="/about/contact_information.html">
       Contact Us
      </a>
      <a href="/about/background/">
       History &amp; Philosophy
      </a>
      <a href="/help/mobile.html">
       Kindle &amp; eReaders
      </a>
      <a href="/help/">
       Help Pages
      </a>
      <a href="/ebooks/offline_catalogs.html">
       Offline Catalogs
      </a>
      <a href="/donate/">
       Donate
      </a>
     </div>
    </div>
    <div class="main-links">
     <a class="link-freq-downloaded" href="/browse/scores/top">
      Frequently Downloaded
     </a>
     <a class="link-main-categories" href="/ebooks/categories">
      Main Categories
     </a>
     <a class="link-reading-lists" href="/ebooks/bookshelf/">
      Reading Lists
     </a>
     <a class="link-advanced-search" href="/ebooks/">
      Search Options
     </a>
    </div>
   </div>
   <div class="tertiary-header">
    <a class="tertiary-link link-freq-downloaded" href="/browse/scores/top">
     Frequently Downloaded
    </a>
    <a class="tertiary-link link-main-categories" href="/ebooks/categories">
     Main Categories
    </a>
   </div>
  </header>
  <div class="container">
   <div class="page_content" id="content">
    <h1>
     <span class="icon icon_search">
     </span>
     All Books (sorted by popularity)
    </h1>
    <div class="body">
     <div>
      <ul class="results">
       <li class="grayed navlink">
        <a accesskey="0" class="link" href="/ebooks/search/?sort_order=title">
         <span class="cell leftcell without-cover">
          <span class="icon-wrapper">
           <span class="icon icon_alpha">
           </span>
          </span>
         </span>
         <span class="cell content">
          <span class="title">
           Sort Alphabetically by Title
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="grayed navlink">
        <a accesskey="1" class="link" href="/ebooks/search/?sort_order=release_date">
         <span class="cell leftcell without-cover">
          <span class="icon-wrapper">
           <span class="icon icon_date">
           </span>
          </span>
         </span>
         <span class="cell content">
          <span class="title">
           Sort by Release Date
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="statusline">
        <div class="padded">
         <span>
          Displaying results 1–25
         </span>
         <span class="links">
          |
          <a accesskey="+" href="/ebooks/search/?sort_order=downloads&amp;start_index=26" title="Go to the next page of results.">
           Next
          </a>
         </span>
        </div>
       </li>
       <li class="booklink">
        <a accesskey="3" class="link" href="/ebooks/2701">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/2701/pg2701.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           Moby Dick; Or, The Whale
          </span>
          <span class="subtitle">
           Herman Melville
          </span>
          <span class="extra">
           109357 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="4" class="link" href="/ebooks/1513">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/1513/pg1513.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           Romeo and Juliet
          </span>
          <span class="subtitle">
           William Shakespeare
          </span>
          <span class="extra">
           79901 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="5" class="link" href="/ebooks/84">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/84/pg84.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           Frankenstein; Or, The Modern Prometheus
          </span>
          <span class="subtitle">
           Mary Wollstonecraft Shelley
          </span>
          <span class="extra">
           78777 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="6" class="link" href="/ebooks/2641">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/2641/pg2641.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           A Room with a View
          </span>
          <span class="subtitle">
           E. M. Forster
          </span>
          <span class="extra">
           63493 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="7" class="link" href="/ebooks/100">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/100/pg100.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           The Complete Works of William Shakespeare
          </span>
          <span class="subtitle">
           William Shakespeare
          </span>
          <span class="extra">
           59579 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="8" class="link" href="/ebooks/1342">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/1342/pg1342.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           Pride and Prejudice
          </span>
          <span class="subtitle">
           Jane Austen
          </span>
          <span class="extra">
           59398 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="9" class="link" href="/ebooks/145">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/145/pg145.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           Middlemarch
          </span>
          <span class="subtitle">
           George Eliot
          </span>
          <span class="extra">
           56093 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="0" class="link" href="/ebooks/37106">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/37106/pg37106.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           Little Women; Or, Meg, Jo, Beth, and Amy
          </span>
          <span class="subtitle">
           Louisa May Alcott
          </span>
          <span class="extra">
           54766 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="1" class="link" href="/ebooks/16389">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/16389/pg16389.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           The Enchanted April
          </span>
          <span class="subtitle">
           Elizabeth Von Arnim
          </span>
          <span class="extra">
           49749 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="2" class="link" href="/ebooks/67979">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/67979/pg67979.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           The Blue Castle: a novel
          </span>
          <span class="subtitle">
           L. M. Montgomery
          </span>
          <span class="extra">
           48034 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="3" class="link" href="/ebooks/11">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/11/pg11.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           Alice's Adventures in Wonderland
          </span>
          <span class="subtitle">
           Lewis Carroll
          </span>
          <span class="extra">
           46226 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="4" class="link" href="/ebooks/394">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/394/pg394.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           Cranford
          </span>
          <span class="subtitle">
           Elizabeth Cleghorn Gaskell
          </span>
          <span class="extra">
           44579 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="5" class="link" href="/ebooks/6761">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/6761/pg6761.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           The Adventures of Ferdinand Count Fathom — Complete
          </span>
          <span class="subtitle">
           T. Smollett
          </span>
          <span class="extra">
           43828 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="6" class="link" href="/ebooks/2160">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/2160/pg2160.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           The Expedition of Humphry Clinker
          </span>
          <span class="subtitle">
           T. Smollett
          </span>
          <span class="extra">
           43817 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="7" class="link" href="/ebooks/6593">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/6593/pg6593.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           History of Tom Jones, a Foundling
          </span>
          <span class="subtitle">
           Henry Fielding
          </span>
          <span class="extra">
           42670 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="8" class="link" href="/ebooks/4085">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/4085/pg4085.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           The Adventures of Roderick Random
          </span>
          <span class="subtitle">
           T. Smollett
          </span>
          <span class="extra">
           42295 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="9" class="link" href="/ebooks/1259">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/1259/pg1259.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           Twenty years after
          </span>
          <span class="subtitle">
           Alexandre Dumas and Auguste Maquet
          </span>
          <span class="extra">
           41825 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="0" class="link" href="/ebooks/5197">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/5197/pg5197.cover.small.jpg"/>
         </span>
         <span class="cell content">
          <span class="title">
           My Life — Volume 1
          </span>
          <span class="subtitle">
           Richard Wagner
          </span>
          <span class="extra">
           41224 downloads
          </span>
         </span>
         <span class="hstrut">
         </span>
        </a>
       </li>
       <li class="booklink">
        <a accesskey="1" class="link" href="/ebooks/33944">
         <span class="cell leftcell with-cover">
          <img alt="" class="cover-thumb" src="/cache/epub/33944/pg33944.cover.small.jpg"/>
         </span>
         <span class="cell content">

In [87]:
soup.find_all("span", class_ = "title")

[<span class="title">Sort Alphabetically by Title</span>,
 <span class="title">Sort by Release Date</span>,
 <span class="title">Moby Dick; Or, The Whale</span>,
 <span class="title">Romeo and Juliet</span>,
 <span class="title">Frankenstein; Or, The Modern Prometheus</span>,
 <span class="title">A Room with a View</span>,
 <span class="title">The Complete Works of William Shakespeare</span>,
 <span class="title">Pride and Prejudice</span>,
 <span class="title">Middlemarch</span>,
 <span class="title">Little Women; Or, Meg, Jo, Beth, and Amy</span>,
 <span class="title">The Enchanted April</span>,
 <span class="title">The Blue Castle: a novel</span>,
 <span class="title">Alice's Adventures in Wonderland</span>,
 <span class="title">Cranford</span>,
 <span class="title">The Adventures of Ferdinand Count Fathom — Complete</span>,
 <span class="title">The Expedition of Humphry Clinker</span>,
 <span class="title">History of Tom Jones, a Foundling</span>,
 <span class="title">The Adventures of Roderick Random</span>,
 <span class="title">Twenty years after</span>,
 <span class="title">My Life — Volume 1</span>,
 <span class="title">How to Observe: Morals and Manners</span>,
 <span class="title">Dracula</span>,
 <span class="title">Crime and Punishment</span>,
 <span class="title">Society in America, Volume 1 (of 2)</span>,
 <span class="title">The Strange Case of Dr. Jekyll and Mr. Hyde</span>,
 <span class="title">The Picture of Dorian Gray</span>,
 <span class="title">Beowulf: An Anglo-Saxon Epic Poem</span>]

In [98]:
titles = []
for title in soup.find_all("span", class_ = "title")[2:]:
    titles.append(title.get_text())
titles

['Moby Dick; Or, The Whale',
 'Romeo and Juliet',
 'Frankenstein; Or, The Modern Prometheus',
 'A Room with a View',
 'The Complete Works of William Shakespeare',
 'Pride and Prejudice',
 'Middlemarch',
 'Little Women; Or, Meg, Jo, Beth, and Amy',
 'The Enchanted April',
 'The Blue Castle: a novel',
 "Alice's Adventures in Wonderland",
 'Cranford',
 'The Adventures of Ferdinand Count Fathom — Complete',
 'The Expedition of Humphry Clinker',
 'History of Tom Jones, a Foundling',
 'The Adventures of Roderick Random',
 'Twenty years after',
 'My Life — Volume 1',
 'How to Observe: Morals and Manners',
 'Dracula',
 'Crime and Punishment',
 'Society in America, Volume 1 (of 2)',
 'The Strange Case of Dr. Jekyll and Mr. Hyde',
 'The Picture of Dorian Gray',
 'Beowulf: An Anglo-Saxon Epic Poem']

In [93]:
for title in soup.find_all("span", class_ = "title")[2:]:
    print(title.get_text())

Moby Dick; Or, The Whale
Romeo and Juliet
Frankenstein; Or, The Modern Prometheus
A Room with a View
The Complete Works of William Shakespeare
Pride and Prejudice
Middlemarch
Little Women; Or, Meg, Jo, Beth, and Amy
The Enchanted April
The Blue Castle: a novel
Alice's Adventures in Wonderland
Cranford
The Adventures of Ferdinand Count Fathom — Complete
The Expedition of Humphry Clinker
History of Tom Jones, a Foundling
The Adventures of Roderick Random
Twenty years after
My Life — Volume 1
How to Observe: Morals and Manners
Dracula
Crime and Punishment
Society in America, Volume 1 (of 2)
The Strange Case of Dr. Jekyll and Mr. Hyde
The Picture of Dorian Gray
Beowulf: An Anglo-Saxon Epic Poem

In [91]:
soup.select("span.title")

[<span class="title">Sort Alphabetically by Title</span>,
 <span class="title">Sort by Release Date</span>,
 <span class="title">Moby Dick; Or, The Whale</span>,
 <span class="title">Romeo and Juliet</span>,
 <span class="title">Frankenstein; Or, The Modern Prometheus</span>,
 <span class="title">A Room with a View</span>,
 <span class="title">The Complete Works of William Shakespeare</span>,
 <span class="title">Pride and Prejudice</span>,
 <span class="title">Middlemarch</span>,
 <span class="title">Little Women; Or, Meg, Jo, Beth, and Amy</span>,
 <span class="title">The Enchanted April</span>,
 <span class="title">The Blue Castle: a novel</span>,
 <span class="title">Alice's Adventures in Wonderland</span>,
 <span class="title">Cranford</span>,
 <span class="title">The Adventures of Ferdinand Count Fathom — Complete</span>,
 <span class="title">The Expedition of Humphry Clinker</span>,
 <span class="title">History of Tom Jones, a Foundling</span>,
 <span class="title">The Adventures of Roderick Random</span>,
 <span class="title">Twenty years after</span>,
 <span class="title">My Life — Volume 1</span>,
 <span class="title">How to Observe: Morals and Manners</span>,
 <span class="title">Dracula</span>,
 <span class="title">Crime and Punishment</span>,
 <span class="title">Society in America, Volume 1 (of 2)</span>,
 <span class="title">The Strange Case of Dr. Jekyll and Mr. Hyde</span>,
 <span class="title">The Picture of Dorian Gray</span>,
 <span class="title">Beowulf: An Anglo-Saxon Epic Poem</span>]

In [119]:
# Retrieve the authors and the number of downloads
authors = []
for author in soup.find_all("span", class_ = "subtitle"):
    authors.append(author.get_text())
authors

['Herman Melville',
 'William Shakespeare',
 'Mary Wollstonecraft Shelley',
 'E. M. Forster',
 'William Shakespeare',
 'Jane Austen',
 'George Eliot',
 'Louisa May Alcott',
 'Elizabeth Von Arnim',
 'L. M. Montgomery',
 'Lewis Carroll',
 'Elizabeth Cleghorn Gaskell',
 'T. Smollett',
 'T. Smollett',
 'Henry Fielding',
 'T. Smollett',
 'Alexandre Dumas and Auguste Maquet',
 'Richard Wagner',
 'Harriet Martineau',
 'Bram Stoker',
 'Fyodor Dostoyevsky',
 'Harriet Martineau',
 'Robert Louis Stevenson',
 'Oscar Wilde']

In [99]:
downloads = []
for download in soup.find_all("span", class_ = "extra"):
    downloads.append(download.get_text())
downloads

['109357 downloads',
 '79901 downloads',
 '78777 downloads',
 '63493 downloads',
 '59579 downloads',
 '59398 downloads',
 '56093 downloads',
 '54766 downloads',
 '49749 downloads',
 '48034 downloads',
 '46226 downloads',
 '44579 downloads',
 '43828 downloads',
 '43817 downloads',
 '42670 downloads',
 '42295 downloads',
 '41825 downloads',
 '41224 downloads',
 '39414 downloads',
 '38150 downloads',
 '32404 downloads',
 '29488 downloads',
 '29426 downloads',
 '28774 downloads',
 '28489 downloads']

In [123]:
downloads_n = []
for download in downloads:
    downloads_n.append(int(download.split(" ")[0]))
downloads_n

[109357,
 79901,
 78777,
 63493,
 59579,
 59398,
 56093,
 54766,
 49749,
 48034,
 46226,
 44579,
 43828,
 43817,
 42670,
 42295,
 41825,
 41224,
 39414,
 38150,
 32404,
 29488,
 29426,
 28774,
 28489]

In [124]:
len(downloads)

25

In [126]:
import pandas as pd

max_len = max(len(titles), len(authors), len(downloads_n))

# Pad each list so they all match in length
titles    = titles    + ["N/A"] * (max_len - len(titles))
authors   = authors   + ["N/A"] * (max_len - len(authors))
downloads_n = downloads_n + ["N/A"] * (max_len - len(downloads_n))

books = pd.DataFrame({
    "title": titles,
    "author": authors,
    "downloads": downloads_n
})
books

,title,author,downloads
0,"Moby Dick; Or, The Whale",Herman Melville,109357
1,Romeo and Juliet,William Shakespeare,79901
2,"Frankenstein; Or, The Modern Prometheus",Mary Wollstonecraft Shelley,78777
3,A Room with a View,E. M. Forster,63493
4,The Complete Works of William Shakespeare,William Shakespeare,59579
5,Pride and Prejudice,Jane Austen,59398
6,Middlemarch,George Eliot,56093
7,"Little Women; Or, Meg, Jo, Beth, and Amy",Louisa May Alcott,54766
8,The Enchanted April,Elizabeth Von Arnim,49749
9,The Blue Castle: a novel,L. M. Montgomery,48034
10,Alice's Adventures in Wonderland,Lewis Carroll,46226
11,Cranford,Elizabeth Cleghorn Gaskell,44579
12,The Adventures of Ferdinand Count Fathom — Com...,T. Smollett,43828
13,The Expedition of Humphry Clinker,T. Smollett,43817
14,"History of Tom Jones, a Foundling",Henry Fielding,42670
15,The Adventures of Roderick Random,T. Smollett,42295
16,Twenty years after,Alexandre Dumas and Auguste Maquet,41825
17,My Life — Volume 1,Richard Wagner,41224
18,How to Observe: Morals and Manners,Harriet Martineau,39414
19,Dracula,Bram Stoker,38150
20,Crime and Punishment,Fyodor Dostoyevsky,32404
21,"Society in America, Volume 1 (of 2)",Harriet Martineau,29488
22,The Strange Case of Dr. Jekyll and Mr. Hyde,Robert Louis Stevenson,29426
23,The Picture of Dorian Gray,Oscar Wilde,28774
24,Beowulf: An Anglo-Saxon Epic Poem,N/A,28489

In [155]:
# Do the same for top 20 (or some top) songs of a genre you like
url = "https://www.popvortex.com/music/charts/top-latin-songs.php"
response = requests.get(url)
response
soup = BeautifulSoup(response.content, "html.parser")

In [156]:
titles = []
for title in soup.find_all("cite", class_ = "title"):
    titles.append(title.get_text())
artists = []
for artist in soup.find_all("em", class_ = "artist"):
    artists.append(artist.get_text())

top100_latin_songs = pd.DataFrame({
    "title":titles,
    "artist":artists
})
top100_latin_songs

                         title                                    artist
0                     NUEVAYoL                                 Bad Bunny
1                        Conga      Gloria Estefan & Miami Sound Machine
2                         DtMF                                 Bad Bunny
3                  Rigo Campos  Los Tucanes de Tijuana & Chalino Sánchez
4           Pelotero A La Bola                         8Uno & Airam Páez
..                         ...                                       ...
95                       Pasta                  Los Dareyes De La Sierra
96  Cuando Yo Era un Jovencito        Ramón Ayala y Sus Bravos del Norte
97                  Luna Llena                              Elvis Crespo
98                 Que Vuelvas               Carín León & Grupo Frontera
99          EL AMOR DE SU VIDA              Grupo Frontera & Grupo Firme

[100 rows x 2 columns]

In [164]:
for line in soup.select("div.chart-content ul li:nth-child(2)"):
    print(line.get_text())

Release Date: January 5, 2025
Release Date: January 1, 1985
Release Date: January 5, 2025
Release Date: May 16, 2025
Release Date: May 16, 2025
Release Date: August 15, 2010
Release Date: January 5, 2025
Release Date: June 22, 1993
Release Date: June 21, 2024
Release Date: September 3, 2024
Release Date: January 1, 2004
Release Date: April 26, 2013
Genre: Regional Mexicano
Release Date: June 2, 1987
Release Date: June 19, 2025
Release Date: July 10, 2025
Release Date: June 24, 2021
Release Date: May 2, 2025
Release Date: June 5, 2025
Release Date: November 17, 2023
Release Date: September 23, 1994
Release Date: May 6, 2022
Release Date: May 23, 2025
Release Date: August 1, 2025
Release Date: May 25, 2023
Release Date: September 3, 2001
Release Date: June 20, 2025
Release Date: June 29, 2017
Release Date: November 16, 2023
Release Date: March 27, 1999
Release Date: November 28, 2005
Release Date: January 1, 1990
Release Date: May 3, 2019
Release Date: January 12, 2017
Release Date: February 8, 2025
Release Date: August 21, 2025
Release Date: October 13, 2023
Release Date: July 11, 1989
Release Date: June 17, 2025
Genre: Salsa y Tropical
Release Date: August 15, 1995
Release Date: August 27, 2001
Release Date: April 4, 1998
Release Date: September 6, 2021
Release Date: June 26, 2025
Release Date: January 1, 2000
Release Date: September 2, 1986
Release Date: June 30, 1995
Release Date: April 21, 2022
Release Date: June 15, 1999
Release Date: September 26, 1995
Release Date: January 1, 1990
Release Date: November 18, 2020
Release Date: March 1, 1988
Release Date: October 18, 2024
Release Date: May 8, 2025
Release Date: October 30, 2020
Release Date: January 1, 1985
Release Date: January 1, 2006
Release Date: January 1, 1991
Release Date: April 20, 2018
Release Date: January 1, 1994
Release Date: January 1, 1989
Release Date: May 8, 2025
Release Date: June 3, 2005
Release Date: January 5, 2025
Release Date: August 15, 1995
Release Date: September 25, 2024
Release Date: December 16, 2022
Release Date: March 17, 2023
Release Date: February 9, 2010
Release Date: June 9, 2025
Release Date: March 19, 2020
Genre: Latin
Release Date: May 6, 2022
Release Date: January 6, 2015
Release Date: January 1, 1998
Release Date: May 1, 2025
Release Date: March 19, 2025
Release Date: January 23, 1986
Release Date: June 26, 2025
Release Date: February 2, 2024
Release Date: February 14, 2025
Release Date: July 24, 2025
Release Date: November 30, 2023
Release Date: January 31, 2025
Release Date: April 17, 2023
Release Date: May 22, 2025
Release Date: July 18, 1995
Release Date: January 5, 2025
Release Date: June 20, 2025
Release Date: June 26, 1995
Release Date: March 12, 2025
Release Date: April 16, 1995
Release Date: October 11, 2018
Release Date: July 31, 2025
Release Date: January 1, 1989
Release Date: April 14, 1998
Release Date: December 9, 2022
Release Date: August 3, 2023

With the parsed HTML, we can now extract specific elements.

#### Extracting Data

`find` and `findAll` (or its equivalent `find_all`) are methods used to search the soup tree for tags that match a certain criterion.

1. **find**:
    - Returns only the **first** tag that matches a given set of criteria.
    - Useful when you know there's only one tag of interest or you only want the first occurrence.
    - Example: If you have multiple `<p>` tags on a page and you use `soup.find('p')`, you'll get only the first `<p>` tag.

2. **findAll (or find_all)**:
    - Returns a **list** of tags that match the given criteria.
    - Useful when you want to capture all occurrences of a particular tag or set of tags.
    - Example: Using `soup.find_all('p')` will give you a list containing all `<p>` tags on the page.

Here's a simple illustration:

```html
<html>
    <body>
        <p>First paragraph.</p>
        <p>Second paragraph.</p>
        <div>Some div.</div>
    </body>
</html>
```

Using `find('p')` would return the "First paragraph." while `find_all('p')` would return a list containing both "First paragraph." and "Second paragraph.".

Let's look at different ways of extracting data.

##### **By Tag**

Let's start with a popular tag: `title`.

In [ ]:
soup.find("title") # Find the first <title> tag on the page

In [ ]:
soup.find_all("title") # Find the all <title> tags on the page

##### **By Class**

To search for HTML elements by class in a webpage using BeautifulSoup, you can also use the `find` and `find_all` methods.

1. **Using `find` method to get the first matching element**:
   
   ```python
   result = soup.find(class_='your-class-name')
   ```

2. **Using `find_all` method to get a list of all matching elements**:

   ```python
   results = soup.find_all(class_='your-class-name')
   ```
   
Note that we are using the `class_` parameter because `class` is a reserved keyword in Python.

Let's dive into our target URL and explore its structure. Our objective is to craft a dataframe populated with bicycle names and their corresponding prices.

To pinpoint the exact tags housing this information, follow these steps:
1. Navigate to the website in your browser.
2. Locate a bicycle name, right-click on it, and choose 'Inspect'. This action will direct you to the element within the site's HTML. Identify the tags so we can extract our desired data.
3. Repeat the same process for the price.

Note: the bicycle names and prices will change depending on the newest bikes in the shop.

Let's filter all elements which `class` is `de-ProductTile-title`.

In [ ]:
soup.find_all(class_='de-ProductTile-title')

In this case, the results of `class` `de-ProductTile-title` are all inside `h4` tags and we actually got the information we wanted. But what if the `class` `de-ProductTile-title` was inside different `tags` and we only want the results of the `tag h4`?

##### **By Tag and Class**

BeautifulSoup allows filtering results using combinations, such as filtering by tag and class.

```python
tags = soup.find_all(name=tag_name, class_=class_name)
```

We can use a for loop to iterate over the results and do whatever we need to do.

To extract the names from the provided HTML content, you can:

1. Use the `find_all` or `findAll` method to locate the `<h4>` tags with the specific class (`de-ProductTile-title` in this case).
2. Extract the text from the found tag.

In [ ]:
# Find all <h4> tags with class "de-ProductTile-title"
bike_names_tags = soup.find_all('h4', class_='de-ProductTile-title')

In [ ]:
# find_all returns a list
bike_names_tags[:3]

In [ ]:
type(bike_names_tags) # What type is it?

In [ ]:
# Lets look at how many elements we retrieved
len(bike_names_tags)

In [ ]:
# Lets look at the first element
bike_names_tags[0]

In [ ]:
# We can get the actual text using .text or .getText()
print(bike_names_tags[0].text)
print(bike_names_tags[0].getText())

In [ ]:
# Lets get rid of all the white spaces
bike_names_tags[0].getText().strip()

In [ ]:
# Create a new list only with bicycle names
names = [bike.text.strip() for bike in bike_names_tags]
names

To extract the price from the provided HTML content, you can:

1. Use the `find_all` method to locate the `<span>` tags with the specific class (`js-de-ProductTile-currentPrice` in this case).
2. Extract the text from the found tag.

In [ ]:
# Find the <span> tag and get its text
prices = soup.find_all('span', class_='js-de-ProductTile-currentPrice')
prices

In [ ]:
prices[0].text

In [ ]:
for price_tag in prices:
    print(price_tag.text)

##### **Getting other attributes**

To access other attribute values such as hyperlinks (which are usually contained in the `href` attribute of `a` tags), you first locate the element using BeautifulSoup methods such as `find` or `find_all`, and then use the `.get()` method to retrieve the value of the attribute you're interested in. Here is a step-by-step explanation:

1. **Locate the element**: Use `find` or `find_all` to locate the element(s) that contain the attribute you want to access.

    ```python
    link_element = soup.find('a', class_='link-class')
    ```

2. **Access the attribute**: Once you have the element, use the `.get()` method to access the attribute value.

    ```python
    link_url = link_element.get('href')
    ```

In the above snippet:
- We first find the `a` element with the class `'link-class'`.
- We then get the value of the `href` attribute which contains the hyperlink.

When inspecting the website, we saw that the bicycle title was a link. How can we get that link?
Lets inspect the whole element containing the bicycle name instead of just the name.

We can see that we have:
    
    <a class="de-u-linkClean js-de-ProductTile-link" href="/collections/mountain-bikes/products/mountain-bike-275-rockrider-st-100-196952-192872">
        
Note: this link will change depending on the newest bike in the shop.

In [ ]:
# Find the <a> tag and get its href attribute
soup.find('a', class_='de-u-linkClean js-de-ProductTile-link').get('href')

In [ ]:
# Extracting all links within <a> tags and class 'de-u-linkClean js-de-ProductTile-link'
for link in soup.find_all('a', class_='de-u-linkClean js-de-ProductTile-link'):
    print(link.get('href'))

#### More filtering options

##### Filtering by Multiple Tags

To find elements with multiple possible tags, you can pass a list of tag names to `find_all`.

In [ ]:
# Find all <div> and <span> tags
soup.find_all(['div', 'span'])

##### Filtering by Multiple Classes

To find elements with multiple possible classes, you can pass a list of class names.

In [ ]:
# Find all elements with class 'js-de-ProductTile-currentPrice' or 'de-ProductTile-title'
soup.find_all(class_=['js-de-ProductTile-currentPrice', 'de-ProductTile-title'])

##### Combining Multiple Criteria

You can combine multiple criteria by using the `attrs` argument.

In [ ]:
# Find all <h4> or <span> tags with class "class1" or "class2"
soup.find_all(['h4', 'span'], attrs={"class": ['js-de-ProductTile-currentPrice', 'de-ProductTile-title']})

##### Limiting the Results

You can limit the number of results returned by `find_all` using the `limit` parameter.

In [ ]:
# Only get the first 5 <h4> tags
soup.find_all('h4', limit=5)

##### Navigating through the "Tree" of HTML Elements

Beautiful Soup provides a robust set of tools that allow you to traverse and explore the hierarchical structure of an HTML document, often referred to as the "tree".

To access child elements directly:

In [ ]:
soup.div.find_all("h4")

The code above will first locate the initial `div` element present in the Beautiful Soup object. Subsequently, it will fetch all `h4` elements contained within that `div`.

But what if you need to retrieve a specific child by its position, say the second child?

In [ ]:
soup.div.find_all("h4")[1]

#### Creating a DataFrame with the data

Instead of getting names and prices separately, we can target the whole component, and extract the name and price from each bicycle component in a more structured manner. By targeting this whole component tag, we can ensure that we are extracting information for the same product (i.e., the name and price correspond to the same bicycle).

Here's how we can achieve this:

1. **Targeting the Whole Component**:
   - Instead of targeting individual tags for names and prices, we target the main component that houses both the name and price.
   - By visually inspecting the HTML, we can see that:
       - The information for each bicycle (name, price, etc.) is grouped together under a `<section>` tag.
       - The `class` attribute of this `<section>` tag is `de-ProductTile-info`. This class seemed specific to the product tile and thus, a good candidate to use for extraction.
   
2. **Iterating through Components**:
   - For each such component, extract the name and the price.
   
3. **Storing Data**:
   - Store the extracted data in lists, which can then be used to create a DataFrame.

In [ ]:
import pandas as pd

# Lists to store extracted data
bicycle_names = []
prices = []

# Find all components
components = soup.find_all('section', class_='de-ProductTile-info')

for component in components:
    # Extract bicycle name
    bike_name = component.find('h4', class_='de-ProductTile-title').text.strip()
    bicycle_names.append(bike_name)

    # Extract price
    price = component.find('span', class_='js-de-ProductTile-currentPrice').text.strip().replace("$", "")
    prices.append(price)

# Create DataFrame
df = pd.DataFrame({
    'Bicycle_Name': bicycle_names,
    'Price': prices
})

df

We could further clean our dataset to ensure the price is a float, facilitating arithmetic operations. This implies prices shouldn't be in a range.

#### 💡 Check for understanding

You are given a raw HTML content of a product list from an online store. Your task is to extract the following details for each product:

- Bicycle Name
- Bicycle Price
- URL for the product details
- URL for the product image

Write a function extract_bike_info that takes in the HTML content and returns a pandas DataFrame with the above columns.

**Hint:**

In order to get the product image, it might be a good idea to use the `article` tag with the class `de-ProductTile` since based on the HTML structure, this `article` tag encapsulates the entire product, including both the image and the product details. This allows us to more easily access all the relevant details for each product without having to jump around different sections.

If we were to only use `soup.find_all('section', class_='de-ProductTile-info')`, we'd be focusing solely on the product details section and would then need a separate approach to extract the image URL. By starting with the `article` tag, we're able to extract all the needed data in a more cohesive and streamlined manner.

**Bonus:** clean the price column so you can make numerical operations.

In [ ]:
def extract_bike_info(soup):
    # your code goes here
    return df

In [ ]:
df = extract_bike_info(soup)
df

#### Scraping many pages

When dealing with a limited number of bicycles, all products are conveniently displayed on a single page. But what if there were numerous products necessitating pagination across multiple pages?

Consider the 'deals' collection. By navigating to the end of its first page on the website, we can observe pagination links. Transitioning to the second page results in a change in the URL:

From:
"https://www.decathlon.com/collections/deals"
To:
"https://www.decathlon.com/collections/deals?page=2"

This pattern in the URL can be leveraged to generate a series of URLs for web scraping.

Please note: Depending on the current offers available at the time of this lesson, pagination might not be present. If that's the case, explore other product categories that have a substantial number of items, resulting in multiple pages.

In [ ]:
pages = [f"https://www.decathlon.com/collections/deals?page={pag}" for pag in range(1,5)]

In [ ]:
pages

Now let's build a df for each URL

In [ ]:
def get_df_from_url(url):

    response = requests.get(url)

    soup = BeautifulSoup(response.content, 'html.parser')
    df = extract_bike_info(soup)
    return df

In [ ]:
dfs = [get_df_from_url(p) for p in pages]

In [ ]:
dfs[1]

In [ ]:
# Concatenate all DataFrames in the list
result_df = pd.concat(dfs, ignore_index=True)
result_df

If you look at our results, and compare it with the website, you'll see that its not returning all the products. Each page has more than 9 products, and its only returning 9 on each page.

This could be because the content is dynamic.

**Dynamic Content**: Many modern websites use JavaScript to load content dynamically. When you make a request using libraries like requests, you only retrieve the initial HTML content. Content loaded dynamically via JavaScript after this won't be captured. In such cases, tools like Selenium are used because they can interact with the JavaScript of the page.

#### CSS selectors

CSS selectors are patterns used to select and manipulate one or more elements in an HTML or XML document. When web scraping with Python, CSS selectors can be used to target specific elements of interest within the page's content.

The `select` method in BeautifulSoup allows you to pass a CSS selector and returns a list of elements matching that selector.

1. **Tag Selector**: Targets elements by their tag name.
   - `p`: selects all `<p>` elements.
   - `soup.select("p")` will retrieve all `<p>` elements

2. **Class Selector**: Targets elements by their class attribute.
   - `.classname`: selects all elements with `class="classname"`.
   - If class name has spaces, they must be changed by `.`
   - `soup.select(".classname")`
   - To combine both, we can have `soup.select("tagname.classname")`

3. **Descendant Selector**: Targets an element that is a descendant of another element.
   - `div p`: selects all `<p>` elements inside a `<div>` element.
   - `.class1 .class2`: selects all elements with class2 that is a descendant of an element with class1.
   
4. **Attribute Selector**: Targets elements based on their attributes and values.
   - `a[href]`: selects all `<a>` elements with an `href` attribute.
   - `a[href="https://www.example.com"]`: selects all `<a>` elements with an `href` value of "https://www.example.com".

And more...

1. **Tag Selector**:
   - **`article`**: This would select all `<article>` elements on the page.

In [ ]:
soup.select("article")

2. **Class Selector**:
   - **`.de-ProductTile`**: This would select all elements with the class `de-ProductTile`.

In [ ]:
soup.select(".de-ProductTile")

To combine both, we can have `soup.select("tagname.classname")`

Without CSS selectors we did:

In [ ]:
# Extracting all links within <a> tags and class 'de-u-linkClean js-de-ProductTile-link'
for link in soup.find_all('a', class_='de-u-linkClean js-de-ProductTile-link'):
    print(link.get('href'))

Equivalently, using CSS selectors, which is a universal syntax, you can try and find `tag_name.class_name`. If class name has spaces, they must be changed by `.`

In [ ]:
# Extracting all links within <a> tags and class 'de-u-linkClean js-de-ProductTile-link'
for link in soup.select('a.de-u-linkClean.js-de-ProductTile-link'):
    print(link.get('href'))

3. **Descendant Selector**:
   - **`.de-ProductTile .de-ProductTile-title`**: This would select all elements with the class `de-ProductTile-title` that are descendants of elements with the class `de-ProductTile`.
   - **`article h4`**: This would select all `<h4>` elements that are descendants of `<article>` elements.

In [ ]:
soup.select(".de-ProductTile .de-ProductTile-title")

In [ ]:
soup.select("article h4")

In [ ]:
# how many spans?
len(soup.select("span"))

In [ ]:
# how many spans inside spans?
len(soup.select("span span"))

In [ ]:
# how many spans inside spans inside spans?
len(soup.select("span span span"))

In [ ]:
# how many span inside div inside div inside div ...
len(soup.select("div div div div div div div div span"))

[Beautiful Soup selectors](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)

You can also use a combination of `find`, `find_all`, and `select` methods to navigate and locate the elements you're interested in more efficiently. Here's how you can use them together:

1. **Using `find` or `find_all` to Narrow Down the Search Scope**:
   
   Initially, you can use `find` or `find_all` to narrow down your search to a specific section of the HTML document.

   ```python
   section = soup.find('div', class_='product-section')
   ```

2. **Using `select` to Further Locate Elements**:

   After narrowing down the section, you can use the `select` method to locate elements using CSS selectors, which allow for more complex queries. The `select` method can be used on a BeautifulSoup object or on a Tag object (like the one retrieved in step 1).

   ```python
   product_links = section.select('a.product-link')
   ```

In this snippet:
- First, we locate a section of the webpage using `find`.
- Then, within that section, we locate all `a` elements with the class `'product-link'` using `select`.

In [ ]:
first_product = soup.find('article', class_='de-ProductTile')
first_product.select('h4.de-ProductTile-title')

In [ ]:
# Since its a list we need to access the element to get the text
first_product.select('h4.de-ProductTile-title')[0].text

### More examples

#### BBC

Lets scrape the BBC to gather some information.

We'll get the hyperlinks to images from the BBC website.

In [ ]:
response = requests.get("https://www.bbc.com/")
response

In [ ]:
soup = BeautifulSoup(response.content, "html.parser")

In [ ]:
img_tags = soup.find_all("img") # We get all the image elements

In [ ]:
len(img_tags) # Lets see how many we got

In [ ]:
img_tags[1] # For example, lets look at the second one to see how we can get the actual URL

In [ ]:
# We can use the get method to get the src attribute which contains the URL to the image
img_tags[1].get("src")

If we inspect the top menu of the BBC, we see that we have the `nav` element with the class `orbit-header-links international`. To get the names from the menu, we need to locate all the span elements inside this nav element.

In [ ]:
# Find the nav element with the specified class
nav_element = soup.find('nav', class_='orbit-header-links international')

# Find all span elements inside the nav element
menu_names = [span.get_text() for span in nav_element.find_all('span')]

# Print the menu names
for name in menu_names:
    print(name)

## Comments

It's always recommended to check for the availability of an **API** before resorting to web scraping for the following reasons:
 * It is generally much easier to use
 * APIs are usually well-documented
 * Utilizing APIs is often preferred by server administrators

Refer to the `robots.txt` file on a website (by doing `www.example.com/robots.txt`) to understand the server's guidelines and limitations regarding web scraping.

## Summary

1. **Web Technologies**:
   - **HTML**: This is the standard markup language that holds the content of the webpage. It is the primary target when we engage in web scraping.
   - **CSS**: Cascading Style Sheets are used to describe the look and formatting of a document written in HTML.
   - **JavaScript**: This is a scripting language used to create and interactive and dynamic website content.

2. **HTML Structure**:
   - **Hierarchical**: HTML documents are structured hierarchically, meaning elements are nested within other elements, forming a tree-like structure.
   - **Tags**: These are the building blocks of HTML, defining elements that hold different types of content.
   - **Attributes**: HTML tags can have attributes, which define properties of an element and are used to set various characteristics such as class, ID, and style.

3. **Web Scraping Tools**:
   - **Requests**: A Python library that allows you to send HTTP requests to get the HTML content of a webpage.
   - **Beautiful Soup**: A Python library that facilitates the programmatic analysis of HTML, helping in parsing the HTML and navigating the parse tree.
   - **Selenium**: In cases where the webpage content is dynamic and generated using JavaScript, tools like Selenium are often used. Selenium can interact with JavaScript to load dynamic content, making it accessible for scraping.
   
4. **Finding and Selecting Elements**:
   - **Selection by Tag, Class, and ID**: We can find elements using various attributes such as their tag name, class name, or ID.
   - **CSS Selectors**: These are patterns used to select elements more complexly, leveraging the relationships between different elements to find them in numerous ways.

## Further materials

[Web archive](http://web.archive.org/): Find the historical state of webpages in the past!

### How to Solve a 403 Error

When you get a `403` status code in response to a web request, it means "Forbidden." The server understands your request, but it refuses to fulfill it. This is often a measure by websites to prevent web scraping or automated access.

Here's why you might get a `403 Forbidden` error:

1. **User-Agent**: Many websites block requests that don't have a standard web browser User-Agent. The default User-Agent of the `requests` library often gets blocked.
2. **Robots.txt**: This is a file websites use to guide web crawlers about which pages or sections of the site shouldn't be processed or scanned. Respect it.
3. **Rate Limiting**: Websites might block you if you make too many requests in a short period.
And more...

To solve it, try the following, starting from the user-agent:

1. **Change the User-Agent**:
   You can mimic a request from a web browser by setting a User-Agent header.
   ```python
   headers = {
       "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
   }
   response = requests.get(url, headers=headers)
   ```

2. **Use a Web Scraper Library**:
   Libraries like Scrapy or Selenium can help bypass restrictions, especially when JavaScript rendering is involved.

3. **Respect `robots.txt`**:
   Always check `https://www.example.com/robots.txt` (replace `example.com` with the website's domain) to see which URLs you're allowed to access.

4. **Rate Limiting**:
   Implement delays in your requests using `time.sleep(seconds)` to avoid hitting rate limits.

5. **Use Proxies or VPN**:
   Rotate IP addresses or use a VPN service if the server has blocked your IP.

6. **Sessions & Cookies**:
   Some websites might require maintaining sessions or handling cookies.