# APIS

![apis_gif](https://media.giphy.com/media/wepUQluC5smgEd4Qz4/giphy.gif)

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#APIS" data-toc-modified-id="APIS-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>APIS</a></span><ul class="toc-item"><li><span><a href="#Web-Communication-Fundamentals" data-toc-modified-id="Web-Communication-Fundamentals-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Web Communication Fundamentals</a></span><ul class="toc-item"><li><span><a href="#DNS,-IP" data-toc-modified-id="DNS,-IP-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>DNS, IP</a></span></li><li><span><a href="#HTTP" data-toc-modified-id="HTTP-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>HTTP</a></span></li><li><span><a href="#URL" data-toc-modified-id="URL-1.1.3"><span class="toc-item-num">1.1.3&nbsp;&nbsp;</span>URL</a></span></li></ul></li><li><span><a href="#HTTP-Requests-and-Responses" data-toc-modified-id="HTTP-Requests-and-Responses-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>HTTP Requests and Responses</a></span><ul class="toc-item"><li><span><a href="#Requests" data-toc-modified-id="Requests-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Requests</a></span></li><li><span><a href="#Response" data-toc-modified-id="Response-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>Response</a></span></li></ul></li><li><span><a href="#APIs" data-toc-modified-id="APIs-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>APIs</a></span><ul class="toc-item"><li><span><a href="#RESTful-APIs" data-toc-modified-id="RESTful-APIs-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>RESTful APIs</a></span></li></ul></li><li><span><a href="#Requests-in-Python" data-toc-modified-id="Requests-in-Python-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Requests in Python</a></span><ul class="toc-item"><li><span><a href="#GET" data-toc-modified-id="GET-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>GET</a></span><ul class="toc-item"><li><span><a href="#Accessing-an-endpoint" data-toc-modified-id="Accessing-an-endpoint-1.4.1.1"><span class="toc-item-num">1.4.1.1&nbsp;&nbsp;</span>Accessing an endpoint</a></span></li><li><span><a href="#Response-headers" data-toc-modified-id="Response-headers-1.4.1.2"><span class="toc-item-num">1.4.1.2&nbsp;&nbsp;</span>Response headers</a></span></li><li><span><a href="#Parameters" data-toc-modified-id="Parameters-1.4.1.3"><span class="toc-item-num">1.4.1.3&nbsp;&nbsp;</span>Parameters</a></span></li><li><span><a href="#Request-Headers" data-toc-modified-id="Request-Headers-1.4.1.4"><span class="toc-item-num">1.4.1.4&nbsp;&nbsp;</span>Request Headers</a></span></li></ul></li></ul></li><li><span><a href="#APIs-examples" data-toc-modified-id="APIs-examples-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>APIs examples</a></span><ul class="toc-item"><li><span><a href="#NewsAPI" data-toc-modified-id="NewsAPI-1.5.1"><span class="toc-item-num">1.5.1&nbsp;&nbsp;</span>NewsAPI</a></span><ul class="toc-item"><li><span><a href="#💡-Check-for-understanding" data-toc-modified-id="💡-Check-for-understanding-1.5.1.1"><span class="toc-item-num">1.5.1.1&nbsp;&nbsp;</span>💡 Check for understanding</a></span></li></ul></li><li><span><a href="#Pokemon-API" data-toc-modified-id="Pokemon-API-1.5.2"><span class="toc-item-num">1.5.2&nbsp;&nbsp;</span>Pokemon API</a></span><ul class="toc-item"><li><span><a href="#json_normalize()" data-toc-modified-id="json_normalize()-1.5.2.1"><span class="toc-item-num">1.5.2.1&nbsp;&nbsp;</span>json_normalize()</a></span></li></ul></li><li><span><a href="#Coincap-API" data-toc-modified-id="Coincap-API-1.5.3"><span class="toc-item-num">1.5.3&nbsp;&nbsp;</span>Coincap API</a></span></li><li><span><a href="#Api-Jokes" data-toc-modified-id="Api-Jokes-1.5.4"><span class="toc-item-num">1.5.4&nbsp;&nbsp;</span>Api Jokes</a></span></li><li><span><a href="#💡-Check-for-understanding" data-toc-modified-id="💡-Check-for-understanding-1.5.5"><span class="toc-item-num">1.5.5&nbsp;&nbsp;</span>💡 Check for understanding</a></span></li></ul></li><li><span><a href="#API-Wrappers" data-toc-modified-id="API-Wrappers-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>API Wrappers</a></span></li><li><span><a href="#Summary" data-toc-modified-id="Summary-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Summary</a></span></li><li><span><a href="#Glossary" data-toc-modified-id="Glossary-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Glossary</a></span></li><li><span><a href="#Further-materials" data-toc-modified-id="Further-materials-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Further materials</a></span></li></ul></li></ul></div>

## Web Communication Fundamentals

![enjuto](https://www.publico.es/files/article_main/uploads//2014/12/13/548bb18f1d9ef.jpg)

### DNS, IP

[How do we connect to www.google.com?](https://www.youtube.com/watch?v=sUhEqT_HSBI&ab_channel=ProfeSang)
* **DNS (Domain Name System)**: it's essentially the phonebook of the internet. Humans access information online through domain names, like "google.com". Web browsers, however, interact through Internet Protocol (IP) addresses. In this example, the DNS maps the internet address www.google.com to the server's IP: 216.58.222.196
 * **IP**: Server identification. A code that allows information to be sent and received by the correct parties
 * **Domain Providers**: Sell and purchase Internet domains

*When making API calls to specific domains, the DNS translates the human-readable domain name into an IP address.*

### HTTP

**H**yper **T**ext **T**ransfer **P**rotocol
- HTTP is a communications protocol that provides a structure for requests between the client and the server on a network.
- For example, the web browser on the user's computer (the client) uses the HTTP protocol to request information from a website on a server.

*We will use APIs that employ the **HTTP** protocol as transport.*

### URL
Contains information about the resource being requested from the **server**.

![](https://github.com/data-bootcamp-v4/lessons/blob/main/img/http.png?raw=true)

Examples:

- https://www.google.com/webhp?authuser=2
- https://www.towardsdatascience.com
- https://www.ironhack.com/
    - Protocol: https (https == http is the same, but https is encrypted)
    - Domain Name --> ironhack
    - TLD (Top-Level Domain) --> .com

*When calling an API, you specify the URL of the API endpoint, which tells the system where to send the request.*

## HTTP Requests and Responses

![](https://github.com/data-bootcamp-v4/lessons/blob/main/img/request-response.png?raw=true)

**Requests** and **responses** are fundamental components of the client-server communication model.

### Requests

These are queries or calls **sent by the client** (such as a web browser or other software) **to the server** in order to receive information (a **response**). 

A request typically consists of:
- A method (such as GET, POST, PUT, DELETE) that defines the action to be performed
     * GET: read the information of the resource, without modifying it in any way. Accessing the website from the browser **gets** information.
- The URL or endpoint specifying the resource
- Optional additional information such as:
    - Headers (metadata): User-Agent, Accept-Language
    - Parameters
    - Body content. 
    
For example, a client might send a GET request to retrieve information from a web page or a POST request to submit form data.

### Response

These are the answers or data sent **by the server back to the client in reply to a request**. 

A response typically includes:
- A status code that indicates the success or failure of the request
- Headers with meta-information about the server's behavior
- The actual content or data (if applicable), such as HTML, JSON (similar to a Python dictionary), images, or other media types.

An important part of the **header** is the **status code**. This code is a numerical value that indicates the server's result. There are different status codes depending on whether the server has managed to carry out the request or has not managed to do anything. These are some groups of status codes:

- **2xx successful**: the request was successfully received, understood, and accepted
- **3xx redirection**: more actions are required to complete the request
- **4xx client error**: the request contains incorrect syntax or cannot be fulfilled
- **5xx server error**: the server has failed to complete an apparently valid request

Complete list:
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

Much more fun:
https://http.cat/

## APIs

**A**pplication **P**rogramming **I**nterface

- APIs define a set of rules and protocols that allow different software applications to communicate with each other.
- The client calls the server through an API, and the server responds.
-  Within a project, the backend may want to share information with the frontend without access to the database.

![](https://github.com/data-bootcamp-v4/lessons/blob/main/img/api.png?raw=true)

### RESTful APIs

As a data analyst, you often need to access data from various sources. RESTful APIs provide a **standardized way** to retrieve, update, or delete data from other systems.

- Usually, **we (the client) send a request, and they (the server) return a response, often in JSON - JavaScript Object Notation - format**. While JSON looks similar to the dictionaries we're used to in Python, it's worth noting that when represented as raw text (e.g., in an API response), the entire JSON structure is a *string*. However, within that structure, JSON can represent various data types like numbers, booleans, and arrays, not just strings.

- APIs always need to provide documentation for their various services: **endpoints**.  Each endpoint is a different URL.  
- Sometimes we have to pass **parameters** to an API endpoint, similar to when we pass parameters to a Python function.

At this point in the Bootcamp, **reading documentation becomes essential**, as each API will "work" differently, and to use it, we will need to know what it requires.

[Here](https://github.com/public-apis/public-apis) is a repository where you can find several free APIs if you feel like exploring a bit.

## Requests in Python

You can make requests to RESTful APIs using libraries like `requests`.

In [ ]:
# If you don't have it installed you can do use using pip or pip3

#!pip install requests

In [2]:
import requests

### GET

Making a `GET request` to the API is simply a call to a `URL` that returns information when provided with the appropriate `parameters`. We will only perform **GET** requests.

Here is an example on how to make a request with Python:

```python
url = "https://api.example.com/products"
response = requests.get(url)

if response.status_code == 200:
    products = response.json()
    # Now you can analyze and work with the products data in Python
```

#### Accessing an endpoint

As we mentioned above, APIs always need to provide documentation for their various services: **endpoints**.  Each endpoint is a different URL.  

**Example: ISS API**

Let's get information from ISS (International Space Station)! We'll start looking at the [ISS API documentation](https://wheretheiss.at/w/developer)

This API allows you to access various data related to the International Space Station (ISS), including its current, past, or future position, timezone information for specific coordinates, and more.

**Key Features**
- **Authentication**: No authentication is currently required, but future endpoints may include this.
- **Rate Limiting**: Limited to approximately 1 request per second.
- **Responses**: Default to JSON format, with optional parameters to modify response appearance.
- **Endpoints**: Several endpoints provide different types of information:
    - **satellites**: Information about satellites, including the ISS.
    - **satellites/[id]**: Position, velocity, and related information for a satellite.
    - **satellites/[id]/positions**: Position data for specific timestamps.
    - **satellites/[id]/tles**: TLE (Two-Line Element Set) data in either JSON or text format.
    - **coordinates/[lat,lon]**: Timezone information for specific coordinates.

**Examples**
- Satellite details: `https://api.wheretheiss.at/v1/satellites`
- ISS position: `https://api.wheretheiss.at/v1/satellites/25544`
- Coordinates information: `https://api.wheretheiss.at/v1/coordinates/37.795517,-122.393693`

**Endpoint satellites**

In [2]:
# We'll use the endpoint satellites, we read it gives us information about satellites

url = "https://api.wheretheiss.at/v1/satellites"

In [3]:
response = requests.get(url) # We use get method to make the request and get information from the API

In [4]:
type(response) # Lets look at the type of the response

requests.models.Response

In [5]:
response.status_code # We can access status code. 200 is OK

200

We can access the response content, which returns a string

In [6]:
response.content

b'[{"name":"iss","id":25544}]'

If response Content-Type is json, we can access it better with `.json()`

In [7]:
info = response.json()

In [8]:
info

[{'name': 'iss', 'id': 25544}]

In [9]:
type(info) # It returns a list of dictionaries

list

In [10]:
info[0]["id"] # So we can access the id like this

25544

#### Response headers 

Response headers are part of the HTTP response that a server sends back to the client after a request has been made. These headers provide meta-information about the response and can affect how the client handles the response.

Here are some common response headers and what they typically represent:

1. **`Date`**: Represents the date and time at which the response was sent.

2. **`Server`**: Provides information about the software used by the originating server.

3. **`X-Rate-Limit`**: Sometimes used in APIs to inform the client about rate limiting policies, such as the number of allowed requests in a given time frame.

4. **`Content-Type`**: Specifies the media type of the resource or data the server is sending back. For example, it could be `application/json` for a JSON object, `text/html` for an HTML page, or `image/png` for an image.

And more.

In [29]:
response.headers # We can also access the response headers

{'Date': 'Tue, 02 Sep 2025 10:42:33 GMT', 'Server': 'Apache/2.2.22 (Ubuntu)', 'X-Powered-By': 'PHP/5.3.10-1ubuntu3.26', 'X-Rate-Limit-Limit': '350', 'X-Rate-Limit-Remaining': '349', 'X-Rate-Limit-Interval': '5 minutes', 'Access-Control-Allow-Origin': '*', 'X-Apache-Time': 'D=15910', 'Cache-Control': 'max-age=0, no-cache', 'Content-Length': '312', 'Keep-Alive': 'timeout=15, max=100', 'Connection': 'Keep-Alive', 'Content-Type': 'application/json'}

#### Parameters

As we mentioned above, sometimes we can pass **parameters** to an API endpoint, similar to when we pass parameters to a Python function.

In the example above, we didn't use any parameters in the endpoint `satellites` since the [documentation]("https://wheretheiss.at/w/developer") said *Parameters: None*.

API parameters are specific values that you include in a request to an API endpoint to filter, sort, or detail the data that you want to retrieve. They allow you to customize the request to get exactly the information you need.

There are several types of parameters that can be used in API requests, such as Path Parameters, Query Parameters, Header Parameters and Request Body Parameters. Let's look at them with an example using another endpoint.

##### 1. **Path Parameters**

These are embedded in the URL path and are used to identify a specific resource. For example, in the URL above `https://api.wheretheiss.at/v1/satellites/25544`, the number `25544` is a path parameter that identifies a specific sattelite.

**Endpoint satellites/id**

Lets use endpoint satellites/[id] with the id we got from the previous endpoint.
Important, we need to provide the whole url for the endpoint as a `string`.

In [13]:
url_iss_position = "https://api.wheretheiss.at/v1/satellites/"+str(info[0]["id"])

In [30]:
response = requests.get(url_iss_position)

In [31]:
response.status_code

200

In [32]:
response.json()

{'name': 'iss',
 'id': 25544,
 'latitude': 43.344694621619,
 'longitude': -86.681350231975,
 'altitude': 422.06256579488,
 'velocity': 27584.380795661,
 'visibility': 'daylight',
 'footprint': 4517.942019117,
 'timestamp': 1756809838,
 'daynum': 2460920.9471991,
 'solar_lat': 7.7341100434845,
 'solar_lon': 18.913922090909,
 'units': 'kilometers'}

Every time we call the endpoint, the information changes since it gives us the current position of the satellite. Let's check that with a loop to gather information at different times.

In [33]:
import time

positions = []

for i in range(10):
    response = requests.get(url_iss_position)
    data = response.json()
    
    positions.append(data)
    time.sleep(0.5)

In [34]:
type(positions) # We created a list with responses

list

In [35]:
type(positions[0]) # Is a list of dictionaries

dict

In [36]:
positions[0] # So we can access each dictionary by its position in the list

{'name': 'iss',
 'id': 25544,
 'latitude': 40.515870502747,
 'longitude': -81.30637152967,
 'altitude': 421.46241946006,
 'velocity': 27584.496510464,
 'visibility': 'daylight',
 'footprint': 4514.8961235321,
 'timestamp': 1756809917,
 'daynum': 2460920.9481134,
 'solar_lat': 7.7337756599181,
 'solar_lon': 18.584681291102,
 'units': 'kilometers'}

In [37]:
positions[9]

{'name': 'iss',
 'id': 25544,
 'latitude': 39.564330605418,
 'longitude': -79.707693149718,
 'altitude': 421.2619296191,
 'velocity': 27584.536932584,
 'visibility': 'daylight',
 'footprint': 4513.8780279185,
 'timestamp': 1756809942,
 'daynum': 2460920.9484028,
 'solar_lat': 7.7336698420501,
 'solar_lon': 18.480491245045,
 'units': 'kilometers'}

Let's extract 10 latitudes from the 10 dictionaries in the list, with 2 decimals.

In [39]:
latitudes = [round(p["latitude"], 2) for p in positions]

In [40]:
latitudes

[40.52, 40.44, 40.33, 40.25, 40.14, 39.99, 39.87, 39.76, 39.68, 39.56]

In [38]:
import pandas as pd
pd.DataFrame(positions) # We can create a dataframe from the API response to work with it better

,name,id,latitude,longitude,altitude,velocity,visibility,footprint,timestamp,daynum,solar_lat,solar_lon,units
0,iss,25544,40.515871,-81.306372,421.462419,27584.496510,daylight,4514.896124,1756809917,2.460921e+06,7.733776,18.584681,kilometers
1,iss,25544,40.440681,-81.176730,421.446534,27584.499718,daylight,4514.815466,1756809919,2.460921e+06,7.733767,18.576346,kilometers
2,iss,25544,40.327588,-80.982843,421.422652,27584.504542,daylight,4514.694207,1756809922,2.460921e+06,7.733754,18.563843,kilometers
3,iss,25544,40.251986,-80.853965,421.406697,27584.507764,daylight,4514.613189,1756809924,2.460921e+06,7.733746,18.555508,kilometers
4,iss,25544,40.138279,-80.661222,421.382713,27584.512608,daylight,4514.491404,1756809927,2.460921e+06,7.733733,18.543005,kilometers
5,iss,25544,39.986103,-80.405292,421.350642,27584.519080,daylight,4514.328546,1756809931,2.460921e+06,7.733716,18.526335,kilometers
6,iss,25544,39.871550,-80.214139,421.326521,27584.523943,daylight,4514.206057,1756809934,2.460921e+06,7.733704,18.513832,kilometers
7,iss,25544,39.756639,-80.023662,421.302345,27584.528812,daylight,4514.083280,1756809937,2.460921e+06,7.733691,18.501329,kilometers
8,iss,25544,39.679833,-79.897049,421.286196,27584.532059,daylight,4514.001270,1756809939,2.460921e+06,7.733683,18.492994,kilometers
9,iss,25544,39.564331,-79.707693,421.261930,27584.536933,daylight,4513.878028,1756809942,2.460921e+06,7.733670,18.480491,kilometers


##### 2. **Query Parameters**

These are added to the end of the URL after a question mark (`?`) and are often used to filter or sort the response. 

For example, in the ISS documentation, it mentions that there is a parameter `units` that can take values `miles` or `kilometers`. So in the URL `https://api.wheretheiss.at/v1/satellites/25544?units=miles`, we added `units=miles` which is a query parameter that shows the data in "miles". 

In general, we add the parameters like this `?param1=value1&param2=value2...` at the end of the URL.

In [41]:
url_iss_position

'https://api.wheretheiss.at/v1/satellites/25544'

In [65]:
# We saw in the documentation that we can add a parameter units to use miles or kilometers

url_iss_position2 = 'https://api.wheretheiss.at/v1/satellites/25544?units=miles'

In [66]:
response = requests.get(url_iss_position2)

In [67]:
response.status_code

200

In [68]:
response.json()

{'name': 'iss',
 'id': 25544,
 'latitude': 26.187486122134,
 'longitude': -63.220427575076,
 'altitude': 260.21001887539,
 'velocity': 17140.330073002,
 'visibility': 'daylight',
 'footprint': 2796.9077185489,
 'timestamp': 1756810251,
 'daynum': 2460920.9519792,
 'solar_lat': 7.7323619180277,
 'solar_lon': 17.192701442878,
 'units': 'miles'}

We can also do it by passing to the argument `params` a dictionary with the parameters in the `get` method.

In [50]:
parameters = {"units": "kilometers"}

In [51]:
url_iss_position

'https://api.wheretheiss.at/v1/satellites/25544'

In [52]:
response = requests.get(
    url=url_iss_position,
    params=parameters
)

In [53]:
response.json()

{'name': 'iss',
 'id': 25544,
 'latitude': 31.67683637633,
 'longitude': -68.997143683258,
 'altitude': 419.69276381479,
 'velocity': 27584.765932806,
 'visibility': 'daylight',
 'footprint': 4505.9000503666,
 'timestamp': 1756810131,
 'daynum': 2460920.9505903,
 'solar_lat': 7.7328698529637,
 'solar_lon': 17.692814104714,
 'units': 'kilometers'}


##### 3. **Header Parameters**

These are included in the request header and can be used for various purposes, such as authentication (e.g., sending an API key or token), content negotiation (e.g., defining the response format), or custom settings defined by the API. If the API requires authentication, you might include an `Authorization` header with your API key.

ISS API mentions that *currently there is no authentication required*. So we'll look at an example with a different API of `authentication` in `header parameters`.

#### Request Headers

Request headers are key-value pairs sent in an HTTP request to provide information about the request itself.

Some request headers are:

1. **Content-Type**: Specifies the media type of the resource or data. Common examples include "application/json" for JSON data, "text/html" for HTML content, and "application/xml" for XML data.

3. **Authorization**: Contains credentials for authenticating the client with the server, often used with tokens or other forms of authentication.

4. **User-Agent**: Provides information about the client (browser or other client), including its version and operating system.


In Python's `requests` library, you can include headers in a request by using the `headers` argument, like this:

```python
headers = {'Content-Type': 'application/json', 'Authorization': 'Bearer YOUR_TOKEN'}
response = requests.get(url, headers=headers)
```

⚠️🚨 ¡Careful with the authentication token! ⚠️🚨  A token is a personal credential for accessing an API, through which your request quota to the API is managed. Therefore, the ideal procedure is to ensure security by storing the token as a variable in an .env file. This way, you can call the environment variable without having to publicly display the token.

**Example: News API**

The *News API* lets you locate articles and breaking news headlines from news sources and blogs across the web.

- Let's look at the [NewsAPI Authentication documentation](https://newsapi.org/docs/authentication). It mentions: 
```
You can attach your API key to a request in one of three ways:

- Via the apiKey querystring parameter.
- Via the X-Api-Key HTTP header.
- Via the Authorization HTTP header. Including Bearer is optional, and be sure not to base 64 encode it like you may have seen in other authentication tutorials.
We strongly recommend the either of last two so that your API key isn't visible to others in logs or via request sniffing.

If you don't append your API key correctly, or your API key is invalid, you will receive a 401 - Unauthorized HTTP error.
```

- Let's look at the documentation for the endpoints to see what **parameters** they accept: [NewsAPI endpoints](https://newsapi.org/docs/endpoints). We see we have the endpoint `/v2/top-headlines` – *returns breaking news headlines for countries, categories, and singular publishers. This is perfect for use with news tickers or anywhere you want to use live up-to-date news headlines.*
If we look at the [documentation of that endpoint](https://newsapi.org/docs/endpoints/top-headlines) we see we have more parameters we can add such as `country` or `category`.

In [ ]:
url = "http://newsapi.org/v2/top-headlines"

In [ ]:
response = requests.get(url)

In [ ]:
response.status_code

Let's try a made up key, using the apiKey querystring parameter. As we read in the documentation, this is not the recommended way.

In [ ]:
url = f"http://newsapi.org/v2/top-headlines?country=us&apiKey=manolonodoesnthavekey"

In [ ]:
url

In [ ]:
response = requests.get(url)

In [ ]:
response.status_code

**4xx**: client error. This means, it is our error.

Lets do with a correct key. You should get your own API key through their website. Once we've saved our key, we'll send it via the X-Api-Key HTTP header.

##### Saving the API Key

Storing an API key directly in your code can expose sensitive information, especially if your code is publicly available (e.g., on a public GitHub repository). The best practice for saving and loading an API key in your code involves the following steps:

1. **Storing the API Key**:
    - **Use Environment Variables**: Store your API key in an environment variable on your system. This keeps the key out of your codebase and allows you to change it without altering your code.


    - **Create a .env File**: If you prefer, you can create a `.env` file (just call it `.env` nothing else before the `.`) in your project directory to store the API key. Inside this file, you would have something like:
   
       ```
       API_KEY=your-api-key-here
       ```

        - **Add .env to .gitignore**: If you're using a version control system like Git, make sure to add the `.env` file to your `.gitignore` file. This prevents the `.env` file (and therefore your API key) from being uploaded to any public repositories. We'll talk about Git and .gitignore in more detail soon.

2. **Load the Key in Your Code**: 

    You can use libraries like `python-dotenv` to load the key into your code. 
    You would need to install `python-dotenv` first.
    ```python 
    !pip install python-dotenv

    from dotenv import load_dotenv
    import os

    load_dotenv()
    api_key = os.getenv("API_KEY")
    ```

       
    Now, `api_key` contains the value of your API key, and you can use it to authenticate your requests to the API.

Lets do the second approach. Lets save it in an env file and save it in a variable.

`Make sure your file is named .env and not .env.txt! Is one of the most common errors. If you need, look at the document properties to make sure it doesn't have .txt at the end even if its not showing the .txt when looking at your folder.`

In [ ]:
#!pip install python-dotenv

In [ ]:
import os
from dotenv import load_dotenv, find_dotenv

load_dotenv()

my_key = os.getenv("API_KEY")

If you get an error, make sure you saved the .env file in the same directory as your jupyter notebook. You can use `os.getcwd()` to do so.

In [ ]:
os.getcwd()

##### Using the API Key in the Header Parameters

In [ ]:
url_top_headlines = "http://newsapi.org/v2/top-headlines"

In [ ]:
parameters = {"country": "us", "category": "science"}

In [ ]:
headers = {"X-Api-Key": my_key}

In [ ]:
response = requests.get(
    url=url_top_headlines, 
    params=parameters, 
    headers=headers
)

In [ ]:
response.status_code

In [ ]:
data = response.json()

In [ ]:
data

## APIs examples

### NewsAPI

In [ ]:
type(data) # response.json() returns a dictionary

In [ ]:
data.keys() # we can get the keys with method keys()

In [ ]:
data.get("status") # we can get a key's value by using get method

In [ ]:
data["totalResults"] # or by using dictionary notation to access values

In [ ]:
# this is the same as above
data.get("totalResults")

`dict[key]` raises error if the key does not exits  
`dict.get(key)` does not raise an error if the key does not exist

In [ ]:
# lets look at the articles
articles = data.get("articles")

In [ ]:
type(articles) # lets see what type it is to know how to access it

In [ ]:
len(articles)

In [ ]:
articles[0] # since articles is a list, we can access its elements by the index

In [ ]:
type(articles[0]) # each element inside the list is a dictionary

In [ ]:
[art["title"] for art in articles] # lets get all the titles using list comprehension

In [ ]:
df = pd.DataFrame(articles) # lets create a dataframe with the articles

In [ ]:
df.head()

#### 💡 Check for understanding

1. What data type is the column *source*?
2. Since the column *source* is not very useful as it is, create a column called *name* that contains only the name inside the column *source*.
3. How many times each unique name appears in the "name" column?

In [ ]:
# Your answer goes here

### Pokemon API

[PokeAPI](https://pokeapi.co/) is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.

In the documentation we see that we can get lot's of data. Let's look at the endpoint *pokemon*: ```https://pokeapi.co/api/v2/pokemon/{id or name}/```

In [16]:
res=requests.get('https://pokeapi.co/api/v2/pokemon/25')
data=res.json()
data

{'abilities': [{'ability': {'name': 'static',
    'url': 'https://pokeapi.co/api/v2/ability/9/'},
   'is_hidden': False,
   'slot': 1},
  {'ability': {'name': 'lightning-rod',
    'url': 'https://pokeapi.co/api/v2/ability/31/'},
   'is_hidden': True,
   'slot': 3}],
 'base_experience': 112,
 'cries': {'latest': 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/latest/25.ogg',
  'legacy': 'https://raw.githubusercontent.com/PokeAPI/cries/main/cries/pokemon/legacy/25.ogg'},
 'forms': [{'name': 'pikachu',
   'url': 'https://pokeapi.co/api/v2/pokemon-form/25/'}],
 'game_indices': [{'game_index': 84,
   'version': {'name': 'red', 'url': 'https://pokeapi.co/api/v2/version/1/'}},
  {'game_index': 84,
   'version': {'name': 'blue', 'url': 'https://pokeapi.co/api/v2/version/2/'}},
  {'game_index': 84,
   'version': {'name': 'yellow',
    'url': 'https://pokeapi.co/api/v2/version/3/'}},
  {'game_index': 25,
   'version': {'name': 'gold', 'url': 'https://pokeapi.co/api/v2/version/4/'}},
  {'game_index': 25,
   'version': {'name': 'silver',
    'url': 'https://pokeapi.co/api/v2/version/5/'}},
  {'game_index': 25,
   'version': {'name': 'crystal',
    'url': 'https://pokeapi.co/api/v2/version/6/'}},
  {'game_index': 25,
   'version': {'name': 'ruby', 'url': 'https://pokeapi.co/api/v2/version/7/'}},
  {'game_index': 25,
   'version': {'name': 'sapphire',
    'url': 'https://pokeapi.co/api/v2/version/8/'}},
  {'game_index': 25,
   'version': {'name': 'emerald',
    'url': 'https://pokeapi.co/api/v2/version/9/'}},
  {'game_index': 25,
   'version': {'name': 'firered',
    'url': 'https://pokeapi.co/api/v2/version/10/'}},
  {'game_index': 25,
   'version': {'name': 'leafgreen',
    'url': 'https://pokeapi.co/api/v2/version/11/'}},
  {'game_index': 25,
   'version': {'name': 'diamond',
    'url': 'https://pokeapi.co/api/v2/version/12/'}},
  {'game_index': 25,
   'version': {'name': 'pearl',
    'url': 'https://pokeapi.co/api/v2/version/13/'}},
  {'game_index': 25,
   'version': {'name': 'platinum',
    'url': 'https://pokeapi.co/api/v2/version/14/'}},
  {'game_index': 25,
   'version': {'name': 'heartgold',
    'url': 'https://pokeapi.co/api/v2/version/15/'}},
  {'game_index': 25,
   'version': {'name': 'soulsilver',
    'url': 'https://pokeapi.co/api/v2/version/16/'}},
  {'game_index': 25,
   'version': {'name': 'black',
    'url': 'https://pokeapi.co/api/v2/version/17/'}},
  {'game_index': 25,
   'version': {'name': 'white',
    'url': 'https://pokeapi.co/api/v2/version/18/'}},
  {'game_index': 25,
   'version': {'name': 'black-2',
    'url': 'https://pokeapi.co/api/v2/version/21/'}},
  {'game_index': 25,
   'version': {'name': 'white-2',
    'url': 'https://pokeapi.co/api/v2/version/22/'}}],
 'height': 4,
 'held_items': [{'item': {'name': 'oran-berry',
    'url': 'https://pokeapi.co/api/v2/item/132/'},
   'version_details': [{'rarity': 50,
     'version': {'name': 'ruby',
      'url': 'https://pokeapi.co/api/v2/version/7/'}},
    {'rarity': 50,
     'version': {'name': 'sapphire',
      'url': 'https://pokeapi.co/api/v2/version/8/'}},
    {'rarity': 50,
     'version': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version/9/'}},
    {'rarity': 50,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'rarity': 50,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'rarity': 50,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}},
    {'rarity': 50,
     'version': {'name': 'heartgold',
      'url': 'https://pokeapi.co/api/v2/version/15/'}},
    {'rarity': 50,
     'version': {'name': 'soulsilver',
      'url': 'https://pokeapi.co/api/v2/version/16/'}},
    {'rarity': 50,
     'version': {'name': 'black',
      'url': 'https://pokeapi.co/api/v2/version/17/'}},
    {'rarity': 50,
     'version': {'name': 'white',
      'url': 'https://pokeapi.co/api/v2/version/18/'}}]},
  {'item': {'name': 'light-ball',
    'url': 'https://pokeapi.co/api/v2/item/213/'},
   'version_details': [{'rarity': 5,
     'version': {'name': 'ruby',
      'url': 'https://pokeapi.co/api/v2/version/7/'}},
    {'rarity': 5,
     'version': {'name': 'sapphire',
      'url': 'https://pokeapi.co/api/v2/version/8/'}},
    {'rarity': 5,
     'version': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version/9/'}},
    {'rarity': 5,
     'version': {'name': 'diamond',
      'url': 'https://pokeapi.co/api/v2/version/12/'}},
    {'rarity': 5,
     'version': {'name': 'pearl',
      'url': 'https://pokeapi.co/api/v2/version/13/'}},
    {'rarity': 5,
     'version': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version/14/'}},
    {'rarity': 5,
     'version': {'name': 'heartgold',
      'url': 'https://pokeapi.co/api/v2/version/15/'}},
    {'rarity': 5,
     'version': {'name': 'soulsilver',
      'url': 'https://pokeapi.co/api/v2/version/16/'}},
    {'rarity': 1,
     'version': {'name': 'black',
      'url': 'https://pokeapi.co/api/v2/version/17/'}},
    {'rarity': 1,
     'version': {'name': 'white',
      'url': 'https://pokeapi.co/api/v2/version/18/'}},
    {'rarity': 5,
     'version': {'name': 'black-2',
      'url': 'https://pokeapi.co/api/v2/version/21/'}},
    {'rarity': 5,
     'version': {'name': 'white-2',
      'url': 'https://pokeapi.co/api/v2/version/22/'}},
    {'rarity': 5,
     'version': {'name': 'x', 'url': 'https://pokeapi.co/api/v2/version/23/'}},
    {'rarity': 5,
     'version': {'name': 'y', 'url': 'https://pokeapi.co/api/v2/version/24/'}},
    {'rarity': 5,
     'version': {'name': 'omega-ruby',
      'url': 'https://pokeapi.co/api/v2/version/25/'}},
    {'rarity': 5,
     'version': {'name': 'alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version/26/'}},
    {'rarity': 5,
     'version': {'name': 'sun',
      'url': 'https://pokeapi.co/api/v2/version/27/'}},
    {'rarity': 5,
     'version': {'name': 'moon',
      'url': 'https://pokeapi.co/api/v2/version/28/'}},
    {'rarity': 5,
     'version': {'name': 'ultra-sun',
      'url': 'https://pokeapi.co/api/v2/version/29/'}},
    {'rarity': 5,
     'version': {'name': 'ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version/30/'}}]}],
 'id': 25,
 'is_default': True,
 'location_area_encounters': 'https://pokeapi.co/api/v2/pokemon/25/encounters',
 'moves': [{'move': {'name': 'mega-punch',
    'url': 'https://pokeapi.co/api/v2/move/5/'},
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'}}]},
  {'move': {'name': 'pay-day', 'url': 'https://pokeapi.co/api/v2/move/6/'},
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'lets-go-pikachu-lets-go-eevee',
      'url': 'https://pokeapi.co/api/v2/version-group/19/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'}}]},
  {'move': {'name': 'thunder-punch',
    'url': 'https://pokeapi.co/api/v2/move/9/'},
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'heartgold-soulsilver',
      'url': 'https://pokeapi.co/api/v2/version-group/10/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'omega-ruby-alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/16/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'ultra-sun-ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/18/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'lets-go-pikachu-lets-go-eevee',
      'url': 'https://pokeapi.co/api/v2/version-group/19/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'scarlet-violet',
      'url': 'https://pokeapi.co/api/v2/version-group/25/'}}]},
  {'move': {'name': 'slam', 'url': 'https://pokeapi.co/api/v2/move/21/'},
   'version_group_details': [{'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
    {'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'}},
    {'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'}},
    {'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'ruby-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/5/'}},
    {'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
    {'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'}},
    {'level_learned_at': 21,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'diamond-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/8/'}},
    {'level_learned_at': 21,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'}},
    {'level_learned_at': 21,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'heartgold-soulsilver',
      'url': 'https://pokeapi.co/api/v2/version-group/10/'}},
    {'level_learned_at': 26,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'black-white',
      'url': 'https://pokeapi.co/api/v2/version-group/11/'}},
    {'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'colosseum',
      'url': 'https://pokeapi.co/api/v2/version-group/12/'}},
    {'level_learned_at': 20,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'xd',
      'url': 'https://pokeapi.co/api/v2/version-group/13/'}},
    {'level_learned_at': 26,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'}},
    {'level_learned_at': 26,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'x-y',
      'url': 'https://pokeapi.co/api/v2/version-group/15/'}},
    {'level_learned_at': 37,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'omega-ruby-alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/16/'}},
    {'level_learned_at': 37,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'sun-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/17/'}},
    {'level_learned_at': 37,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'ultra-sun-ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/18/'}},
    {'level_learned_at': 24,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'lets-go-pikachu-lets-go-eevee',
      'url': 'https://pokeapi.co/api/v2/version-group/19/'}},
    {'level_learned_at': 28,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'}},
    {'level_learned_at': 28,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'brilliant-diamond-and-shining-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/23/'}}]},
  {'move': {'name': 'double-kick',
    'url': 'https://pokeapi.co/api/v2/move/24/'},
   'version_group_details': [{'level_learned_at': 9,
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None,
     'version_group': {'name': 'lets-go-pikachu-lets-go-eevee',
      'url': 'https://pokeapi.co/api/v2/version-group/19/'}}]},
  {'move': {'name': 'mega-kick', 'url': 'https://pokeapi.co/api/v2/move/25/'},
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'}}]},
  {'move': {'name': 'headbutt', 'url': 'https://pokeapi.co/api/v2/move/29/'},
   'version_group_details': [{'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'}},
    {'level_learned_at': 0,
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None,
     'version_group': {'name': 'crystal',

In [13]:
for i in range(1,152):
    res=requests.get('https://pokeapi.co/api/v2/pokemon/'+str(i))
    res.status_code
    data=res.json()
    print(data["forms"][0]["name"])

bulbasaur
ivysaur
venusaur
charmander
charmeleon
charizard
squirtle
wartortle
blastoise
caterpie
metapod
butterfree
weedle
kakuna
beedrill
pidgey
pidgeotto
pidgeot
rattata
raticate
spearow
fearow
ekans
arbok
pikachu
raichu
sandshrew
sandslash
nidoran-f
nidorina
nidoqueen
nidoran-m
nidorino
nidoking
clefairy
clefable
vulpix
ninetales
jigglypuff
wigglytuff
zubat
golbat
oddish
gloom
vileplume
paras
parasect
venonat
venomoth
diglett
dugtrio
meowth
persian
psyduck
golduck
mankey
primeape
growlithe
arcanine
poliwag
poliwhirl
poliwrath
abra
kadabra
alakazam
machop
machoke
machamp
bellsprout
weepinbell
victreebel
tentacool
tentacruel
geodude
graveler
golem
ponyta
rapidash
slowpoke
slowbro
magnemite
magneton
farfetchd
doduo
dodrio
seel
dewgong
grimer
muk
shellder
cloyster
gastly
haunter
gengar
onix
drowzee
hypno
krabby
kingler
voltorb
electrode
exeggcute
exeggutor
cubone
marowak
hitmonlee
hitmonchan
lickitung
koffing
weezing
rhyhorn
rhydon
chansey
tangela
kangaskhan
horsea
seadra
goldeen
seaking
staryu
starmie
mr-mime
scyther
jynx
electabuzz
magmar
pinsir
tauros
magikarp
gyarados
lapras
ditto
eevee
vaporeon
jolteon
flareon
porygon
omanyte
omastar
kabuto
kabutops
aerodactyl
snorlax
articuno
zapdos
moltres
dratini
dragonair
dragonite
mewtwo
mew

In [9]:
data=res.json()
data

'charizard'

In [17]:
type(data)

dict

In [18]:
data.keys()

dict_keys(['abilities', 'base_experience', 'cries', 'forms', 'game_indices', 'height', 'held_items', 'id', 'is_default', 'location_area_encounters', 'moves', 'name', 'order', 'past_abilities', 'past_types', 'species', 'sprites', 'stats', 'types', 'weight'])

In [19]:
# Lets look at the following attributes
print(data["name"])
print(data["weight"])
print(data["sprites"])

pikachu
60
{'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png', 'back_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/female/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/25.png', 'back_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/female/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/female/25.png', 'other': {'dream_world': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/25.svg', 'front_female': None}, 'home': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/shiny/female/25.png'}, 'official-artwork': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/25.png'}, 'showdown': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/back/25.gif', 'back_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/back/female/25.gif', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/back/shiny/25.gif', 'back_shiny_female': None, 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/25.gif', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/female/25.gif', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/shiny/25.gif', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/shiny/female/25.gif'}}, 'versions': {'generation-i': {'red-blue': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/back/25.png', 'back_gray': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/back/gray/25.png', 'back_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/back/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/25.png', 'front_gray': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/gray/25.png', 'front_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/25.png'}, 'yellow': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/back/25.png', 'back_gray': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/back/gray/25.png', 'back_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/transparent/back/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/25.png', 'front_gray': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/gray/25.png', 'front_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/yellow/transparent/25.png'}}, 'generation-ii': {'crystal': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/back/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/back/shiny/25.png', 'back_shiny_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/transparent/back/shiny/25.png', 'back_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/transparent/back/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/shiny/25.png', 'front_shiny_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/transparent/shiny/25.png', 'front_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/crystal/transparent/25.png'}, 'gold': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/gold/back/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/gold/back/shiny/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/gold/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/gold/shiny/25.png', 'front_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/gold/transparent/25.png'}, 'silver': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/silver/back/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/silver/back/shiny/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/silver/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/silver/shiny/25.png', 'front_transparent': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ii/silver/transparent/25.png'}}, 'generation-iii': {'emerald': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/emerald/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/emerald/shiny/25.png'}, 'firered-leafgreen': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/firered-leafgreen/back/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/firered-leafgreen/back/shiny/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/firered-leafgreen/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/firered-leafgreen/shiny/25.png'}, 'ruby-sapphire': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/ruby-sapphire/back/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/ruby-sapphire/back/shiny/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/ruby-sapphire/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/ruby-sapphire/shiny/25.png'}}, 'generation-iv': {'diamond-pearl': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/back/25.png', 'back_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/back/female/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/back/shiny/25.png', 'back_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/back/shiny/female/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/shiny/female/25.png'}, 'heartgold-soulsilver': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/back/25.png', 'back_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/back/female/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/back/shiny/25.png', 'back_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/back/shiny/female/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/shiny/female/25.png'}, 'platinum': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/back/25.png', 'back_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/back/female/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/back/shiny/25.png', 'back_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/back/shiny/female/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/shiny/female/25.png'}}, 'generation-v': {'black-white': {'animated': {'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/back/25.gif', 'back_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/back/female/25.gif', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/back/shiny/25.gif', 'back_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/back/shiny/female/25.gif', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/25.gif', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/female/25.gif', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/shiny/25.gif', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/shiny/female/25.gif'}, 'back_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/back/25.png', 'back_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/back/female/25.png', 'back_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/back/shiny/25.png', 'back_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/back/shiny/female/25.png', 'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/shiny/female/25.png'}}, 'generation-vi': {'omegaruby-alphasapphire': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/shiny/female/25.png'}, 'x-y': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/x-y/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/x-y/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/x-y/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/x-y/shiny/female/25.png'}}, 'generation-vii': {'icons': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/icons/25.png', 'front_female': None}, 'ultra-sun-ultra-moon': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/female/25.png', 'front_shiny': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/shiny/25.png', 'front_shiny_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/shiny/female/25.png'}}, 'generation-viii': {'icons': {'front_default': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-viii/icons/25.png', 'front_female': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-viii/icons/female/25.png'}}}}

In [20]:
# Lets get the pokemon image from sprites - front_default.
# Remember we can read the documentation to understand how to get all the information
data['sprites']['front_default']

'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png'

We will define a function, `get_pokemon`, that takes an ID number as input. This function fetches details about a Pokémon from the PokeAPI using the given ID, extracts its name, weight, and front-facing image, and then returns this data in a dictionary format. If the ID is invalid or there's an issue with the request, a ValueError is raised.

In [21]:
def get_pokemon(id_number):
    res=requests.get(f'https://pokeapi.co/api/v2/pokemon/{id_number}')
    
    if(res.status_code==200):
        data = res.json()
        return {"id": id_number,'name':data['name'], "weight":data["weight"],'image':data['sprites']['front_default']}
    else:
        raise ValueError("Cannot get pokemon, id does not exist")

In [22]:
get_pokemon(25) # Lets use the function for pokemon id 25

{'id': 25,
 'name': 'pikachu',
 'weight': 60,
 'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png'}

In [23]:
[get_pokemon(i+1) for i in range(5)] # Lets use list comprehension to gather information for the first 5 pokemons

[{'id': 1,
  'name': 'bulbasaur',
  'weight': 69,
  'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png'},
 {'id': 2,
  'name': 'ivysaur',
  'weight': 130,
  'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png'},
 {'id': 3,
  'name': 'venusaur',
  'weight': 1000,
  'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png'},
 {'id': 4,
  'name': 'charmander',
  'weight': 85,
  'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png'},
 {'id': 5,
  'name': 'charmeleon',
  'weight': 190,
  'image': 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png'}]

We will now define a function, `print_pokemon`, that takes in a Pokémon dictionary and displays its ID, name, weight, and its image.

In [26]:
from IPython.display import Image

def print_pokemon(poke):
    print(str(poke["id"])+" " +poke["name"]+ " "+str(poke["weight"]/10) + " kg")
    display(Image(url=poke['image']))

After defining this function, we will retrieve and display details for the first 10 Pokémon by iterating through their IDs and using both the `get_pokemon` and `print_pokemon` functions.

In [28]:
[print_pokemon(get_pokemon(i+1)) for i in range(151)]

1 bulbasaur 6.9 kg

2 ivysaur 13.0 kg

3 venusaur 100.0 kg

4 charmander 8.5 kg

5 charmeleon 19.0 kg

6 charizard 90.5 kg

7 squirtle 9.0 kg

8 wartortle 22.5 kg

9 blastoise 85.5 kg

10 caterpie 2.9 kg

11 metapod 9.9 kg

12 butterfree 32.0 kg

13 weedle 3.2 kg

14 kakuna 10.0 kg

15 beedrill 29.5 kg

16 pidgey 1.8 kg

17 pidgeotto 30.0 kg

18 pidgeot 39.5 kg

19 rattata 3.5 kg

20 raticate 18.5 kg

21 spearow 2.0 kg

22 fearow 38.0 kg

23 ekans 6.9 kg

24 arbok 65.0 kg

25 pikachu 6.0 kg

26 raichu 30.0 kg

27 sandshrew 12.0 kg

28 sandslash 29.5 kg

29 nidoran-f 7.0 kg

30 nidorina 20.0 kg

31 nidoqueen 60.0 kg

32 nidoran-m 9.0 kg

33 nidorino 19.5 kg

34 nidoking 62.0 kg

35 clefairy 7.5 kg

36 clefable 40.0 kg

37 vulpix 9.9 kg

38 ninetales 19.9 kg

39 jigglypuff 5.5 kg

40 wigglytuff 12.0 kg

41 zubat 7.5 kg

42 golbat 55.0 kg

43 oddish 5.4 kg

44 gloom 8.6 kg

45 vileplume 18.6 kg

46 paras 5.4 kg

47 parasect 29.5 kg

48 venonat 30.0 kg

49 venomoth 12.5 kg

50 diglett 0.8 kg

51 dugtrio 33.3 kg

52 meowth 4.2 kg

53 persian 32.0 kg

54 psyduck 19.6 kg

55 golduck 76.6 kg

56 mankey 28.0 kg

57 primeape 32.0 kg

58 growlithe 19.0 kg

59 arcanine 155.0 kg

60 poliwag 12.4 kg

61 poliwhirl 20.0 kg

62 poliwrath 54.0 kg

63 abra 19.5 kg

64 kadabra 56.5 kg

65 alakazam 48.0 kg

66 machop 19.5 kg

67 machoke 70.5 kg

68 machamp 130.0 kg

69 bellsprout 4.0 kg

70 weepinbell 6.4 kg

71 victreebel 15.5 kg

72 tentacool 45.5 kg

73 tentacruel 55.0 kg

74 geodude 20.0 kg

75 graveler 105.0 kg

76 golem 300.0 kg

77 ponyta 30.0 kg

78 rapidash 95.0 kg

79 slowpoke 36.0 kg

80 slowbro 78.5 kg

81 magnemite 6.0 kg

82 magneton 60.0 kg

83 farfetchd 15.0 kg

84 doduo 39.2 kg

85 dodrio 85.2 kg

86 seel 90.0 kg

87 dewgong 120.0 kg

88 grimer 30.0 kg

89 muk 30.0 kg

90 shellder 4.0 kg

91 cloyster 132.5 kg

92 gastly 0.1 kg

93 haunter 0.1 kg

94 gengar 40.5 kg

95 onix 210.0 kg

96 drowzee 32.4 kg

97 hypno 75.6 kg

98 krabby 6.5 kg

99 kingler 60.0 kg

100 voltorb 10.4 kg

101 electrode 66.6 kg

102 exeggcute 2.5 kg

103 exeggutor 120.0 kg

104 cubone 6.5 kg

105 marowak 45.0 kg

106 hitmonlee 49.8 kg

107 hitmonchan 50.2 kg

108 lickitung 65.5 kg

109 koffing 1.0 kg

110 weezing 9.5 kg

111 rhyhorn 115.0 kg

112 rhydon 120.0 kg

113 chansey 34.6 kg

114 tangela 35.0 kg

115 kangaskhan 80.0 kg

116 horsea 8.0 kg

117 seadra 25.0 kg

118 goldeen 15.0 kg

119 seaking 39.0 kg

120 staryu 34.5 kg

121 starmie 80.0 kg

122 mr-mime 54.5 kg

123 scyther 56.0 kg

124 jynx 40.6 kg

125 electabuzz 30.0 kg

126 magmar 44.5 kg

127 pinsir 55.0 kg

128 tauros 88.4 kg

129 magikarp 10.0 kg

130 gyarados 235.0 kg

131 lapras 220.0 kg

132 ditto 4.0 kg

133 eevee 6.5 kg

134 vaporeon 29.0 kg

135 jolteon 24.5 kg

136 flareon 25.0 kg

137 porygon 36.5 kg

138 omanyte 7.5 kg

139 omastar 35.0 kg

140 kabuto 11.5 kg

141 kabutops 40.5 kg

142 aerodactyl 59.0 kg

143 snorlax 460.0 kg

144 articuno 55.4 kg

145 zapdos 52.6 kg

146 moltres 60.0 kg

147 dratini 3.3 kg

148 dragonair 16.5 kg

149 dragonite 210.0 kg

150 mewtwo 122.0 kg

151 mew 4.0 kg

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

#### json_normalize()

Want the data as a DataFrame instead of a dictionary?

The following line creates a DataFrame from the items of the dictionary data. Each key-value pair will be treated as a row, with two columns: the first for the key and the second for the value.

In [30]:
import pandas as pd

In [31]:
df = pd.DataFrame(data.items())
df

,0,1
0,abilities,"[{'ability': {'name': 'static', 'url': 'https:..."
1,base_experience,112
2,cries,{'latest': 'https://raw.githubusercontent.com/...
3,forms,"[{'name': 'pikachu', 'url': 'https://pokeapi.c..."
4,game_indices,"[{'game_index': 84, 'version': {'name': 'red',..."
5,height,4
6,held_items,"[{'item': {'name': 'oran-berry', 'url': 'https..."
7,id,25
8,is_default,True
9,location_area_encounters,https://pokeapi.co/api/v2/pokemon/25/encounters
10,moves,"[{'move': {'name': 'mega-punch', 'url': 'https..."
11,name,pikachu
12,order,35
13,past_abilities,"[{'abilities': [{'ability': None, 'is_hidden':..."
14,past_types,[]
15,species,"{'name': 'pikachu', 'url': 'https://pokeapi.co..."
16,sprites,{'back_default': 'https://raw.githubuserconten...
17,stats,"[{'base_stat': 35, 'effort': 0, 'stat': {'name..."
18,types,"[{'slot': 1, 'type': {'name': 'electric', 'url..."
19,weight,60

That format is still very hard to work with. Lets use `json_normalize` instead. `json_normalize` is used to normalize semi-structured JSON data into a flat table (DataFrame). It's particularly useful when dealing with nested dictionaries or lists inside JSON.

In [36]:
df = pd.json_normalize(data)
df

,abilities,base_experience,forms,game_indices,height,held_items,id,is_default,location_area_encounters,moves,...,sprites.versions.generation-vi.x-y.front_shiny,sprites.versions.generation-vi.x-y.front_shiny_female,sprites.versions.generation-vii.icons.front_default,sprites.versions.generation-vii.icons.front_female,sprites.versions.generation-vii.ultra-sun-ultra-moon.front_default,sprites.versions.generation-vii.ultra-sun-ultra-moon.front_female,sprites.versions.generation-vii.ultra-sun-ultra-moon.front_shiny,sprites.versions.generation-vii.ultra-sun-ultra-moon.front_shiny_female,sprites.versions.generation-viii.icons.front_default,sprites.versions.generation-viii.icons.front_female
0,"[{'ability': {'name': 'static', 'url': 'https:...",112,"[{'name': 'pikachu', 'url': 'https://pokeapi.c...","[{'game_index': 84, 'version': {'name': 'red',...",4,"[{'item': {'name': 'oran-berry', 'url': 'https...",25,True,https://pokeapi.co/api/v2/pokemon/25/encounters,"[{'move': {'name': 'mega-punch', 'url': 'https...",...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,None,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...,https://raw.githubusercontent.com/PokeAPI/spri...

A lot better, even though we still have nested dictionaries or lists inside the dataframe.

Let's see again the difference between creating a dataframe directly or using `json_normalize` by using `data["abilities"]`.

In [37]:
pd.DataFrame(data["abilities"])

                                             ability  is_hidden  slot
0  {'name': 'static', 'url': 'https://pokeapi.co/...      False     1
1  {'name': 'lightning-rod', 'url': 'https://poke...       True     3

In [38]:
pd.json_normalize(data["abilities"])

   is_hidden  slot   ability.name                            ability.url
0      False     1         static   https://pokeapi.co/api/v2/ability/9/
1       True     3  lightning-rod  https://pokeapi.co/api/v2/ability/31/

### Coincap API

CoinCap is a useful tool for real-time pricing and market activity for over 1,000 cryptocurrencies. Check the documentation at https://docs.coincap.io/

In [ ]:
url = "http://api.coincap.io/v2/assets"

In [ ]:
response = requests.get(url)

In [ ]:
print(response)

In [ ]:
res = response.json()

In [ ]:
res # it returns a dictionary with all the data

In [ ]:
# Again, let's try to have it as a dataframe
data = pd.DataFrame(res["data"])
data.head()

In [ ]:
# Lets see if the result would differ in this case using json_normalize
pd.json_normalize(res["data"])

### Api Jokes

JokeAPI is a REST API that serves uniformly and well formatted jokes.
It can be used without any API token, membership, registration or payment.
It supports a variety of filters that can be applied to get just the right jokes you need.
Check the documentation here: https://jokeapi.dev/

In [39]:
url_random_joke = "https://v2.jokeapi.dev/joke/dark?amount=3"
request = requests.get(url_random_joke).json()
request

{'error': False,
 'amount': 3,
 'jokes': [{'category': 'Dark',
   'type': 'single',
   'joke': "My grandfather says I'm too reliant on technology.\nI called him a hypocrite and unplugged his life support.",
   'flags': {'nsfw': False,
    'religious': False,
    'political': False,
    'racist': False,
    'sexist': False,
    'explicit': False},
   'id': 177,
   'safe': False,
   'lang': 'en'},
  {'category': 'Dark',
   'type': 'twopart',
   'setup': "I had a granny that we couldn't decide whether to bury or cremate",
   'delivery': 'In the end we decided to just let her live.',
   'flags': {'nsfw': False,
    'religious': False,
    'political': False,
    'racist': False,
    'sexist': False,
    'explicit': False},
   'id': 67,
   'safe': False,
   'lang': 'en'},
  {'category': 'Dark',
   'type': 'single',
   'joke': "I didn't vaccinate my 10 kids and the one that survived is fine!",
   'flags': {'nsfw': False,
    'religious': False,
    'political': False,
    'racist': False,
    'sexist': False,
    'explicit': False},
   'id': 95,
   'safe': False,
   'lang': 'en'}]}

### 💡 Check for understanding

Choose one API from the [Public APIs list](https://github.com/public-apis/public-apis). Attempt to call your selected API, either with or without parameters, and retrieve some valuable information. Document your findings.

In [46]:
res=requests.get('https://www.googleapis.com/books/v1/volumes/858oEyeN1N8C')
data=res.json()
data

{'kind': 'books#volume',
 'id': '858oEyeN1N8C',
 'etag': 'jk4Jnd9rah4',
 'selfLink': 'https://www.googleapis.com/books/v1/volumes/858oEyeN1N8C',
 'volumeInfo': {'title': "A Room of One's Own",
  'authors': ['Virginia Woolf'],
  'publisher': 'Broadview Press',
  'publishedDate': '2001-11-27',
  'description': "&quot;But, you may say, we asked you to speak about women and fiction—what has that got to do with a room of one's own? I will try to explain.&quot; So begins what is widely regarded as the foundation text of feminist literary criticism, Virginia Woolf's A Room of One's Own. Probably Woolf's most readable and entertaining book, it was based on papers delivered at Newnham and Girton Colleges—the two women's colleges at Cambridge University. Never losing sight of her undergraduate audience, Woolf provides a brief history of women's writing in English, a scathing account of the subtle and not so subtle ways in which women have been discouraged from writing, and a recommendation for how to change matters: &quot;a woman must have money and a room of her own if she is to write fiction.&quot; In the process, Woolf takes on women's economic disadvantages, the underfunding of women's education, the discouragement of women from certain kinds of (lucrative) work, the ways in which women are socialized into suspicion of each other, and how women participate in their own systemic oppression. Yet, in spite of these weighty subjects, A Room of One's Own remains throughout funny, light-hearted, engaging for the novice reader while still offering &quot;nuggets&quot; to the worldy-wise. It is, above and beyond all else, a very model of essay writing. This Broadview edition provides a reliable text at a very reasonable price. It contains textual notes but no appendices or introduction.",
  'industryIdentifiers': [{'type': 'ISBN_10', 'identifier': '177048325X'},
   {'type': 'ISBN_13', 'identifier': '9781770483255'}],
  'readingModes': {'text': True, 'image': True},
  'pageCount': 134,
  'printedPageCount': 137,
  'dimensions': {'height': '21.60 cm', 'width': '14.00 cm'},
  'printType': 'BOOK',
  'categories': ['Literary Criticism / Feminist',
   'Literary Criticism / General',
   'Social Science / Feminism & Feminist Theory'],
  'maturityRating': 'NOT_MATURE',
  'allowAnonLogging': True,
  'contentVersion': '0.5.4.0.preview.3',
  'panelizationSummary': {'containsEpubBubbles': False,
   'containsImageBubbles': False},
  'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=858oEyeN1N8C&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE72s9KpPMdnltEB0va7kdc4qtOK7qXCNvH33EDIZHKRw-FwiBO8-ZdPMnbFnm99AT01CT6ZppAhaMxKUF1beVBfVy0-gJ9JIofjnHO7y9_aXi4ULIh6p-DhZi0XWtn5Qz9lyO5yK&source=gbs_api',
   'thumbnail': 'http://books.google.com/books/content?id=858oEyeN1N8C&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE71opYQql8zKd2_wam56pcpmw_LnMcTe0NyGGdi44sR8uc_wAkCg_IsBSFe6dV7s6JdYm9OuxsGVBpPPlO77mbfV1FOIkyYRtfDu22blU38QQGMrHiWbUd49hEywlXYUoVkXbptV&source=gbs_api',
   'small': 'http://books.google.com/books/content?id=858oEyeN1N8C&printsec=frontcover&img=1&zoom=2&edge=curl&imgtk=AFLRE7348A1PPGiDuswE_Jl8cbEbDBtcEfmmnycU4C_tcL4D283qmFp31FbftkN2jJ9oy6oAp72ym6u93F4VOTX50bFQkjCtyGLtxy1edeCLavRwtg3_VAdaAGYgNt64flJ5yQ2erwV_&source=gbs_api',
   'medium': 'http://books.google.com/books/content?id=858oEyeN1N8C&printsec=frontcover&img=1&zoom=3&edge=curl&imgtk=AFLRE70PPGLSc7t4ThE04556yXAeH3sjT2yIWfn_dO2gE9BNBh0g-SbbIX43RYZnCQL6cqOks72WyxSeYfWF2kBJ8DN1Cn9WauyU3DYhEy1hJrj_IgJw63PmTlUZGsiVj3loObyi2DcA&source=gbs_api',
   'large': 'http://books.google.com/books/content?id=858oEyeN1N8C&printsec=frontcover&img=1&zoom=4&edge=curl&imgtk=AFLRE73T_VZCXFGNHSj6neSevxVjJfRywt4xzjHSU02E_9fY4IofcoFDPeCBrDSTaFJ9LZKLymWjtGUjeNWSu1TR0H1oPM5a2ou7TvTCzwU-aL6h3IW19ynemfBgA2H8CdfKtp9kv56M&source=gbs_api',
   'extraLarge': 'http://books.google.com/books/content?id=858oEyeN1N8C&printsec=frontcover&img=1&zoom=6&edge=curl&imgtk=AFLRE72ZYQtw7PBuveqwWDSuMvfHmLJqd68zwHaTJ-hAG-3ZfyTd9om-Nwk3PzZbalUzrwQLx95oAowM5EUsXG9YcJ-2_x_iLBvOHw20VdT1xOMXScRWo0qHJvCMs3LMCac-AVhVo8XF&source=gbs_api'},
  'language': 'en',
  'previewLink': 'http://books.google.de/books?id=858oEyeN1N8C&hl=&source=gbs_api',
  'infoLink': 'https://play.google.com/store/books/details?id=858oEyeN1N8C&source=gbs_api',
  'canonicalVolumeLink': 'https://play.google.com/store/books/details?id=858oEyeN1N8C'},
 'layerInfo': {'layers': [{'layerId': 'geo',
    'volumeAnnotationsVersion': '6'}]},
 'saleInfo': {'country': 'DE',
  'saleability': 'FOR_SALE_AND_RENTAL',
  'isEbook': True,
  'listPrice': {'amount': 9.76, 'currencyCode': 'EUR'},
  'retailPrice': {'amount': 6.83, 'currencyCode': 'EUR'},
  'buyLink': 'https://play.google.com/store/books/details?id=858oEyeN1N8C&rdid=book-858oEyeN1N8C&rdot=1&source=gbs_api',
  'offers': [{'finskyOfferType': 1,
    'listPrice': {'amountInMicros': 9760000, 'currencyCode': 'EUR'},
    'retailPrice': {'amountInMicros': 6830000, 'currencyCode': 'EUR'},
    'giftable': True},
   {'finskyOfferType': 3,
    'listPrice': {'amountInMicros': 8300000, 'currencyCode': 'EUR'},
    'retailPrice': {'amountInMicros': 6150000, 'currencyCode': 'EUR'},
    'rentalDuration': {'unit': 'DAY', 'count': 180}}]},
 'accessInfo': {'country': 'DE',
  'viewability': 'PARTIAL',
  'embeddable': True,
  'publicDomain': False,
  'textToSpeechPermission': 'ALLOWED',
  'epub': {'isAvailable': True,
   'acsTokenLink': 'http://books.google.de/books/download/A_Room_of_One_s_Own-sample-epub.acsm?id=858oEyeN1N8C&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api'},
  'pdf': {'isAvailable': True,
   'acsTokenLink': 'http://books.google.de/books/download/A_Room_of_One_s_Own-sample-pdf.acsm?id=858oEyeN1N8C&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api'},
  'webReaderLink': 'http://play.google.com/books/reader?id=858oEyeN1N8C&hl=&source=gbs_api',
  'accessViewStatus': 'SAMPLE',
  'quoteSharingAllowed': False}}

In [51]:
data["volumeInfo"]["description"]

"&quot;But, you may say, we asked you to speak about women and fiction—what has that got to do with a room of one's own? I will try to explain.&quot; So begins what is widely regarded as the foundation text of feminist literary criticism, Virginia Woolf's A Room of One's Own. Probably Woolf's most readable and entertaining book, it was based on papers delivered at Newnham and Girton Colleges—the two women's colleges at Cambridge University. Never losing sight of her undergraduate audience, Woolf provides a brief history of women's writing in English, a scathing account of the subtle and not so subtle ways in which women have been discouraged from writing, and a recommendation for how to change matters: &quot;a woman must have money and a room of her own if she is to write fiction.&quot; In the process, Woolf takes on women's economic disadvantages, the underfunding of women's education, the discouragement of women from certain kinds of (lucrative) work, the ways in which women are socialized into suspicion of each other, and how women participate in their own systemic oppression. Yet, in spite of these weighty subjects, A Room of One's Own remains throughout funny, light-hearted, engaging for the novice reader while still offering &quot;nuggets&quot; to the worldy-wise. It is, above and beyond all else, a very model of essay writing. This Broadview edition provides a reliable text at a very reasonable price. It contains textual notes but no appendices or introduction."

In [84]:
data["items"]

[{'kind': 'books#volume',
  'id': 'Jau4EAAAQBAJ',
  'etag': 'Afxoi6rcabk',
  'selfLink': 'https://www.googleapis.com/books/v1/volumes/Jau4EAAAQBAJ',
  'volumeInfo': {'title': 'Die Wellen',
   'subtitle': 'Roman',
   'authors': ['Virginia Woolf'],
   'publisher': 'S. Fischer Verlag',
   'publishedDate': '2023-12-06',
   'description': '»Ein Klassiker. Es ist ihr größtes Buch.« E. M. Forster Es ist eines der radikalsten und eigenwilligsten Experimente des zwanzigsten Jahrhunderts: Virginia Woolfs changierende und vielfarbig instrumentierte Beschwörung von Bernard, Louis, Neville, Rhoda, Jinny und Susan. Sechs ganz unterschiedliche Stimmen formen die Intensität der Kindheit, die Zuversicht und sinnliche Erfahrung der Jugend, das Losgelöstsein des mittleren Alters. Sinneswahrnehmungen, Emotionen, Reflexionen kommen und gehen im Voranschreiten des Erzählstroms wie die Jahreszeiten, wie die Wellen, die Sonne.',
   'industryIdentifiers': [{'type': 'ISBN_13', 'identifier': '9783104918563'},
    {'type': 'ISBN_10', 'identifier': '3104918562'}],
   'readingModes': {'text': True, 'image': True},
   'pageCount': 371,
   'printType': 'BOOK',
   'categories': ['Fiction'],
   'maturityRating': 'NOT_MATURE',
   'allowAnonLogging': False,
   'contentVersion': '1.6.5.0.preview.3',
   'panelizationSummary': {'containsEpubBubbles': False,
    'containsImageBubbles': False},
   'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=Jau4EAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api',
    'thumbnail': 'http://books.google.com/books/content?id=Jau4EAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'},
   'language': 'de',
   'previewLink': 'http://books.google.de/books?id=Jau4EAAAQBAJ&printsec=frontcover&dq=inauthor:woolf&hl=&cd=1&source=gbs_api',
   'infoLink': 'https://play.google.com/store/books/details?id=Jau4EAAAQBAJ&source=gbs_api',
   'canonicalVolumeLink': 'https://play.google.com/store/books/details?id=Jau4EAAAQBAJ'},
  'saleInfo': {'country': 'DE',
   'saleability': 'FOR_SALE',
   'isEbook': True,
   'listPrice': {'amount': 12.99, 'currencyCode': 'EUR'},
   'retailPrice': {'amount': 12.99, 'currencyCode': 'EUR'},
   'buyLink': 'https://play.google.com/store/books/details?id=Jau4EAAAQBAJ&rdid=book-Jau4EAAAQBAJ&rdot=1&source=gbs_api',
   'offers': [{'finskyOfferType': 1,
     'listPrice': {'amountInMicros': 12990000, 'currencyCode': 'EUR'},
     'retailPrice': {'amountInMicros': 12990000, 'currencyCode': 'EUR'},
     'giftable': True}]},
  'accessInfo': {'country': 'DE',
   'viewability': 'PARTIAL',
   'embeddable': True,
   'publicDomain': False,
   'textToSpeechPermission': 'ALLOWED',
   'epub': {'isAvailable': True,
    'acsTokenLink': 'http://books.google.de/books/download/Die_Wellen-sample-epub.acsm?id=Jau4EAAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api'},
   'pdf': {'isAvailable': True,
    'acsTokenLink': 'http://books.google.de/books/download/Die_Wellen-sample-pdf.acsm?id=Jau4EAAAQBAJ&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api'},
   'webReaderLink': 'http://play.google.com/books/reader?id=Jau4EAAAQBAJ&hl=&source=gbs_api',
   'accessViewStatus': 'SAMPLE',
   'quoteSharingAllowed': False},
  'searchInfo': {'textSnippet': 'Sinneswahrnehmungen, Emotionen, Reflexionen kommen und gehen im Voranschreiten des Erzählstroms wie die Jahreszeiten, wie die Wellen, die Sonne.'}},
 {'kind': 'books#volume',
  'id': 'ZNSnEAAAQBAJ',
  'etag': '67mZL4k86do',
  'selfLink': 'https://www.googleapis.com/books/v1/volumes/ZNSnEAAAQBAJ',
  'volumeInfo': {'title': 'Fahrt zum Leuchtturm',
   'authors': ['Virginia Woolf'],
   'publisher': 'epubli',
   'publishedDate': '2023-01-10',
   'description': 'To the Lighthouse ist ein Roman von Virginia Woolf aus dem Jahr 1927. Der Text, damals ein bahnbrechender Roman der Hochmoderne, konzentriert sich auf die Familie Ramsay und ihre Besuche auf der Isle of Skye in Schottland zwischen den Jahren 1910 und 1920 und spielt dabei gekonnt mit zeitlichen Ebenen. Mit diesem Roman knüpft Virginia Woolf an die Tradition modernistischer Romanautoren wie Marcel Proust und James Joyce an, bei denen die Romanhandlung der philosophischen Selbsterforschung untergeordnet ist. Der Roman enthält nur wenige Dialoge und kaum Handlungsstränge. Der größte Teil des Inhalts behandelt die Gedanken und Beobachtungen der Romanfiguren. Zu den vielen Tropen und Themen des Buches gehören Verlust, Subjektivität und das Problem der Wahrnehmung. 1998 wurde To the Lighthouse von der Modern Library auf Platz 15 ihrer Liste der 100 besten englischsprachigen Romane des 20. Jahrhunderts gesetzt. 2005 wurde der Roman vom TIME Magazine zu einem der hundert besten englischsprachigen Romane von 1923 bis heute gewählt.',
   'industryIdentifiers': [{'type': 'ISBN_13', 'identifier': '9783757506872'},
    {'type': 'ISBN_10', 'identifier': '3757506871'}],
   'readingModes': {'text': True, 'image': True},
   'pageCount': 288,
   'printType': 'BOOK',
   'categories': ['Family & Relationships'],
   'maturityRating': 'NOT_MATURE',
   'allowAnonLogging': False,
   'contentVersion': '0.1.1.0.preview.3',
   'panelizationSummary': {'containsEpubBubbles': False,
    'containsImageBubbles': False},
   'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=ZNSnEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api',
    'thumbnail': 'http://books.google.com/books/content?id=ZNSnEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'},
   'language': 'de',
   'previewLink': 'http://books.google.de/books?id=ZNSnEAAAQBAJ&printsec=frontcover&dq=inauthor:woolf&hl=&cd=2&source=gbs_api',
   'infoLink': 'https://play.google.com/store/books/details?id=ZNSnEAAAQBAJ&source=gbs_api',
   'canonicalVolumeLink': 'https://play.google.com/store/books/details?id=ZNSnEAAAQBAJ'},
  'saleInfo': {'country': 'DE',
   'saleability': 'FOR_SALE',
   'isEbook': True,
   'listPrice': {'amount': 1.49, 'currencyCode': 'EUR'},
   'retailPrice': {'amount': 1.49, 'currencyCode': 'EUR'},
   'buyLink': 'https://play.google.com/store/books/details?id=ZNSnEAAAQBAJ&rdid=book-ZNSnEAAAQBAJ&rdot=1&source=gbs_api',
   'offers': [{'finskyOfferType': 1,
     'listPrice': {'amountInMicros': 1490000, 'currencyCode': 'EUR'},
     'retailPrice': {'amountInMicros': 1490000, 'currencyCode': 'EUR'},
     'giftable': True}]},
  'accessInfo': {'country': 'DE',
   'viewability': 'PARTIAL',
   'embeddable': True,
   'publicDomain': False,
   'textToSpeechPermission': 'ALLOWED',
   'epub': {'isAvailable': True},
   'pdf': {'isAvailable': True},
   'webReaderLink': 'http://play.google.com/books/reader?id=ZNSnEAAAQBAJ&hl=&source=gbs_api',
   'accessViewStatus': 'SAMPLE',
   'quoteSharingAllowed': False},
  'searchInfo': {'textSnippet': 'Mit diesem Roman knüpft Virginia Woolf an die Tradition modernistischer Romanautoren wie Marcel Proust und James Joyce an, bei denen die Romanhandlung der philosophischen Selbsterforschung untergeordnet ist.'}},
 {'kind': 'books#volume',
  'id': 'fbCqDwAAQBAJ',
  'etag': '000YMHUjxLI',
  'selfLink': 'https://www.googleapis.com/books/v1/volumes/fbCqDwAAQBAJ',
  'volumeInfo': {'title': 'Virginia Woolf: Die Fahrt zum Leuchtturm',
   'authors': ['Virginia Woolf'],
   'publisher': ' eClassica',
   'publishedDate': '2019-08-23',
   'description': 'Virginia Woolf: Die Fahrt zum Leuchtturm | Neu lektorierte 2019er-Ausgabe. Mit modernisierter Rechtschreibung, voll verlinkt, mit eBook-Inhaltsverzeichnis Im Jahr 2015 wählten 82 internationale Literaturkritiker Virginia Woolfs ›To the Lighthouse‹ zum zweit-bedeutendsten britischen Roman. aller Zeiten. Nicht von ungefähr: Woolfs brillanter Erzählstil ermöglicht es, eine Geschichte, die vor allem von reflektierender Innenschau geprägt ist, in einer Spannung zu erzählen, dass man das Buch nicht mehr aus der Hand legen kann. Im Zentrum steht die Familie Ramsay und deren Besuche im Sommerhaus auf der schottischen Isle of Skye, vor und nach dem Ersten Weltkrieg. Symbolisch wie real ragt im Hintergrund der malerische Leuchtturm von Godrevy Point auf, den man den Kindern bald zu besuchen verspricht. Doch subkutane, kaum wahrnehmbare häusliche Konflikte, von Woolf wie mit einem Seziermesser herausgeschält, sabotieren die Fahrt. Erst viele Jahre später findet sie statt. Doch alles hat sich bis dahin verändert. – Der Roman wurde schon kurz nach seinem Erscheinen als grandioses Stück Literatur gefeiert und verkaufte sich besser als alle Romane von Virginia Woolf zuvor.',
   'readingModes': {'text': True, 'image': False},
   'pageCount': 229,
   'printType': 'BOOK',
   'categories': ['Fiction'],
   'maturityRating': 'NOT_MATURE',
   'allowAnonLogging': False,
   'contentVersion': '1.2.2.0.preview.2',
   'panelizationSummary': {'containsEpubBubbles': False,
    'containsImageBubbles': False},
   'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=fbCqDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api',
    'thumbnail': 'http://books.google.com/books/content?id=fbCqDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'},
   'language': 'de',
   'previewLink': 'http://books.google.de/books?id=fbCqDwAAQBAJ&printsec=frontcover&dq=inauthor:woolf&hl=&cd=3&source=gbs_api',
   'infoLink': 'https://play.google.com/store/books/details?id=fbCqDwAAQBAJ&source=gbs_api',
   'canonicalVolumeLink': 'https://play.google.com/store/books/details?id=fbCqDwAAQBAJ'},
  'saleInfo': {'country': 'DE',
   'saleability': 'FOR_SALE',
   'isEbook': True,
   'listPrice': {'amount': 2.13, 'currencyCode': 'EUR'},
   'retailPrice': {'amount': 2.13, 'currencyCode': 'EUR'},
   'buyLink': 'https://play.google.com/store/books/details?id=fbCqDwAAQBAJ&rdid=book-fbCqDwAAQBAJ&rdot=1&source=gbs_api',
   'offers': [{'finskyOfferType': 1,
     'listPrice': {'amountInMicros': 2130000, 'currencyCode': 'EUR'},
     'retailPrice': {'amountInMicros': 2130000, 'currencyCode': 'EUR'},
     'giftable': True}]},
  'accessInfo': {'country': 'DE',
   'viewability': 'PARTIAL',
   'embeddable': True,
   'publicDomain': False,
   'textToSpeechPermission': 'ALLOWED',
   'epub': {'isAvailable': True,
    'acsTokenLink': 'http://books.google.de/books/download/Virginia_Woolf_Die_Fahrt_zum_Leuchtturm-sample-epub.acsm?id=fbCqDwAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api'},
   'pdf': {'isAvailable': False},
   'webReaderLink': 'http://play.google.com/books/reader?id=fbCqDwAAQBAJ&hl=&source=gbs_api',
   'accessViewStatus': 'SAMPLE',
   'quoteSharingAllowed': False},
  'searchInfo': {'textSnippet': 'Virginia Woolf: Die Fahrt zum Leuchtturm | Neu lektorierte 2019er-Ausgabe.'}},
 {'kind': 'books#volume',
  'id': 'M0KpEAAAQBAJ',
  'etag': 'TeYZlR34Nco',
  'selfLink': 'https://www.googleapis.com/books/v1/volumes/M0KpEAAAQBAJ',
  'volumeInfo': {'title': 'Die Fahrt zum Leuchtturm',
   'authors': ['Virginia Woolf'],
   'publisher': 'SAGA Egmont',
   'publishedDate': '2020-08-17',
   'description': 'Einer der großen Romane Virginia Woolfs, den ihr Mann Leonard als "philosophisches Gedicht" bezeichnete: Im Zentrum der Geschichte, die sich über ungefähr 10 Jahre erstreckt, stehen die einfühlsame Mrs Ramsay und ihre Großfamilie. Auf ihrem Landhaus auf der schottischen Insel Skye beherbergt sie viele Gäste, wobei es weniger um die Aktivitäten als solche geht, sondern um das Interagieren der unterschiedlichen Familienmitglieder und Sommergäste untereinander.-',
   'industryIdentifiers': [{'type': 'ISBN_13', 'identifier': '9788726643008'},
    {'type': 'ISBN_10', 'identifier': '8726643006'}],
   'readingModes': {'text': True, 'image': True},
   'pageCount': 250,
   'printType': 'BOOK',
   'categories': ['Fiction'],
   'maturityRating': 'NOT_MATURE',
   'allowAnonLogging': False,
   'contentVersion': '0.4.4.0.preview.3',
   'panelizationSummary': {'containsEpubBubbles': False,
    'containsImageBubbles': False},
   'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=M0KpEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api',
    'thumbnail': 'http://books.google.com/books/content?id=M0KpEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'},
   'language': 'de',
   'previewLink': 'http://books.google.de/books?id=M0KpEAAAQBAJ&printsec=frontcover&dq=inauthor:woolf&hl=&cd=4&source=gbs_api',
   'infoLink': 'https://play.google.com/store/books/details?id=M0KpEAAAQBAJ&source=gbs_api',
   'canonicalVolumeLink': 'https://play.google.com/store/books/details?id=M0KpEAAAQBAJ'},
  'saleInfo': {'country': 'DE',
   'saleability': 'FOR_SALE',
   'isEbook': True,
   'listPrice': {'amount': 9.99, 'currencyCode': 'EUR'},
   'retailPrice': {'amount': 9.99, 'currencyCode': 'EUR'},
   'buyLink': 'https://play.google.com/store/books/details?id=M0KpEAAAQBAJ&rdid=book-M0KpEAAAQBAJ&rdot=1&source=gbs_api',
   'offers': [{'finskyOfferType': 1,
     'listPrice': {'amountInMicros': 9990000, 'currencyCode': 'EUR'},
     'retailPrice': {'amountInMicros': 9990000, 'currencyCode': 'EUR'},
     'giftable': True}]},
  'accessInfo': {'country': 'DE',
   'viewability': 'PARTIAL',
   'embeddable': True,
   'publicDomain': False,
   'textToSpeechPermission': 'ALLOWED',
   'epub': {'isAvailable': True,
    'acsTokenLink': 'http://books.google.de/books/download/Die_Fahrt_zum_Leuchtturm-sample-epub.acsm?id=M0KpEAAAQBAJ&format=epub&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api'},
   'pdf': {'isAvailable': True,
    'acsTokenLink': 'http://books.google.de/books/download/Die_Fahrt_zum_Leuchtturm-sample-pdf.acsm?id=M0KpEAAAQBAJ&format=pdf&output=acs4_fulfillment_token&dl_type=sample&source=gbs_api'},
   'webReaderLink': 'http://play.google.com/books/reader?id=M0KpEAAAQBAJ&hl=&source=gbs_api',
   'accessViewStatus': 'SAMPLE',
   'quoteSharingAllowed': False},
  'searchInfo': {'textSnippet': 'Einer der großen Romane Virginia Woolfs, den ihr Mann Leonard als &quot;philosophisches Gedicht&quot; bezeichnete: Im Zentrum der Geschichte, die sich über ungefähr 10 Jahre erstreckt, stehen die einfühlsame Mrs Ramsay und ihre Großfamilie.'}},
 {'kind': 'books#volume',
  'id': 'Y1SDEAAAQBAJ',
  'etag': 'oBET/IB7Qi0',
  'selfLink': 'https://www.googleapis.com/books/v1/volumes/Y1SDEAAAQBAJ',
  'volumeInfo': {'title': 'Ein eigenes Zimmer',
   'authors': ['Virginia Woolf'],
   'publisher': 'epubli',
   'publishedDate': '2022-08-19',
   'description': 'Das Essay "A Room of One\'s Own" wurde erstmals im September 1929 veröffentlicht wurde. Der Text basiert auf zwei Vorlesungen, die Virginia Woolf im Oktober 1928 am Newnham College und am Girton College, den Frauenhochschulen der Universität Cambridge, hielt. Woolf stellt dabei fest, dass das Fehlen weiblicher Fiktion in der Literaturgeschichte eher auf einen Mangel an Möglichkeiten als auf weniger literarisches Talent zurückzuführen ist. In dem Essay verwendet Woolf verschiedene Metaphern, um die soziale Benachteiligung der Frau am Bespiel der Literatur zu erörtern. Die Hauptschlussfolgerung ihrer Arbeit lässt sich auf folgende Formel verdichten: Eine Frau muss Geld und ein eigenes Zimmer haben, um Romane schreiben zu können. Finanzielle Sicherheit und ein Raum des Rückzugs sind von elementarer Bedeutung für den kreativen literarischen Prozess. Die Differenz im literarischen Output zwischen den Geschlechter am Beginn des 20. Jahrhunderts lässt sich nach Ansicht von Woolf im Wesentlichen auf den Mangel dieser beiden elementaren Faktoren bezogen auf das weibliche Geschlecht zurückführen.',
   'industryIdentifiers': [{'type': 'ISBN_13', 'identifier': '9783756523610'},
    {'type': 'ISBN_10', 'identifier': '3756523616'}],
   'readingModes': {'text': True, 'image': True},
   'pageCount': 150,
   'printType': 'BOOK',
   'categories': ['Literary Criticism'],
   'maturityRating': 'NOT_MATURE',
   'allowAnonLogging': False,
   'contentVersion': '0.2.2.0.preview.3',
   'panelizationSummary': {'containsEpubBubbles': False,
    'containsImageBubbles': False},
   'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=Y1SDEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api',
    'thumbnail': 'http://books.google.com/books/content?id=Y1SDEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'},
   'language': 'de',
   'previewLink': 'http://books.google.de/books?id=Y1SDEAAAQBAJ&printsec=frontcover&dq=inauthor:woolf&hl=&cd=5&source=gbs_api',
   'infoLink': 'https://play.google.com/store/books/details?id=Y1SDEAAAQBAJ&source=gbs_api',
   'canonicalVolumeLink': 'https://play.google.com/store/books/details?id=Y1SDEAAAQBAJ'},
  'saleInfo': {'country': 'DE',
   'saleability': 'FOR_SALE',
   'isEbook': True,
   'listPrice': {'amount': 4.99, 'currencyCode': 'EUR'},
   'retailPrice': {'amount': 4.99, 'currencyCode': 'EUR'},
   'buyLink': 'https://play.google.com/store/books/details?id=Y1SDEAAAQBAJ&rdid=book-Y1SDEAAAQBAJ&rdot=1&source=gbs_api',
   'offers': [{'finskyOfferType': 1,
     'listPrice': {'amountInMicros': 4990000, 'currencyCode': 'EUR'},
     'retailPrice': {'amountInMicros': 4990000, 'currencyCode': 'EUR'},
     'giftable': True}]},
  'accessInfo': {'country': 'DE',
   'viewability': 'PARTIAL',
   'embeddable': True,
   'publicDomain': False,
   'textToSpeechPermission': 'ALLOWED',
   'epub': {'isAvailable': True},
   'pdf': {'isAvailable': True},
   'webReaderLink': 'http://play.google.com/books/reader?id=Y1SDEAAAQBAJ&hl=&source=gbs_api',
   'accessViewStatus': 'SAMPLE',
   'quoteSharingAllowed': False},
  'searchInfo': {'textSnippet': 'Die Hauptschlussfolgerung ihrer Arbeit lässt sich auf folgende Formel verdichten: Eine Frau muss Geld und ein eigenes Zimmer haben, um Romane schreiben zu können.'}},
 {'kind': 'books#volume',
  'id': 'UlS3PQAACAAJ',
  'etag': 'Jf51Xpm3Nqc',
  'selfLink': 'https://www.googleapis.com/books/v1/volumes/UlS3PQAACAAJ',
  'volumeInfo': {'title': 'Flush',
   'subtitle': 'eine Biographie',
   'authors': ['Virginia Woolf'],
   'publishedDate': '1994',
   'industryIdentifiers': [{'type': 'ISBN_10', 'identifier': '3596124166'},
    {'type': 'ISBN_13', 'identifier': '9783596124169'}],
   'readingModes': {'text': False, 'image': False},
   'pageCount': 130,
   'printType': 'BOOK',
   'categories': ['Dogs'],
   'maturityRating': 'NOT_MATURE',
   'allowAnonLogging': False,
   'contentVersion': 'preview-1.0.0',
   'imageLinks': {'smallThumbnail': 'http://books.google.com/books/content?id=UlS3PQAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api',
    'thumbnail': 'http://books.google.com/books/content?id=UlS3PQAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api'},
   'language': 'de',
   'previewLink': 'http://books.google.de/books?id=UlS3PQAACAAJ&dq=inauthor:woolf&hl=&cd=6&source=gbs_api',
   'infoLink': 'http://books.google.de/books?id=UlS3PQAACAAJ&dq=inauthor:woolf&hl=&source=gbs_api',
   'canonicalVolumeLink': 'https://books.google.com/books/about/Flush.html?hl=&id=UlS3PQAACAAJ'},
  'saleInfo': {'country': 'DE',
   'saleability': 'NOT_FOR_SALE',
   'isEbook': False},
  'accessInfo': {'country': 'DE',
   'viewability': 'NO_PAGES',
   'embeddable': False,
   'publicDomain': False,
   'textToSpeechPermission': 'ALLOWED',
   'epub': {'isAvailable': False},
   'pdf': {'isAvailable': False},
   'webReaderLink': 'http://play.google.com/books/reader?id=UlS3PQAACAAJ&hl=&source=gbs_api',
   'accessViewStatus': 'NONE',
   'quoteSharingAllowed': False}},
 {'kind': 'books#volume',
  'id': 'KiaaDQAAQBAJ',
  'etag': 'w4m5MHlZPbo',
  'selfLink': 'https://www.googleapis.com/books/v1/volumes/KiaaDQAAQBAJ',
  'volumeInfo': {'title': 'Flush',
   'subtitle': 'Eine Biographie',
   'authors': ['Virginia Woolf'],
   'publisher': 'S. Fischer Verlag',
   'publishedDate': '2016-12-08',

In [116]:
url = 'https://www.googleapis.com/books/v1/volumes'
params = {
    "q": "inauthor:woolf",
    "langRestrict": "en" 
}
res = requests.get(url, params=params)
data = res.json()

In [115]:
from IPython.display import Image, display, HTML

res=requests.get('https://www.googleapis.com/books/v1/volumes?q=inauthor:woolf')
data=res.json()

titles =[]
image_links = []
descriptions = []
for item in data.get("items", []):
    volume = item.get("volumeInfo", {})
    titles.append(volume.get("title", "Untitled"))
    image_links.append(volume.get("imageLinks", {}).get("smallThumbnail", "N/A"))
    descriptions.append(volume.get("description", "N/A"))


virginia_wolf = pd.DataFrame({
    "title":titles,
    "description":descriptions,
    "image_link":image_links
})

virginia_wolf["image"] = virginia_wolf["image_link"].apply(
    lambda x: f'<img src="{x}" width="80">' if x != "N/A" else "N/A"
)

virginia_wolf.drop(columns=["image_link"], inplace=True)

display(HTML(virginia_wolf.to_html(escape=False)))

In [117]:
from IPython.display import Image, display, HTML

url = 'https://www.googleapis.com/books/v1/volumes'
params = {
    "q": "inauthor:woolf",
    "langRestrict": "en" 
}
res = requests.get(url, params=params)
data = res.json()

titles =[]
image_links = []
descriptions = []
for item in data.get("items", []):
    volume = item.get("volumeInfo", {})
    titles.append(volume.get("title", "Untitled"))
    image_links.append(volume.get("imageLinks", {}).get("smallThumbnail", "N/A"))
    descriptions.append(volume.get("description", "N/A"))


virginia_wolf = pd.DataFrame({
    "title":titles,
    "description":descriptions,
    "image_link":image_links
})

virginia_wolf["image"] = virginia_wolf["image_link"].apply(
    lambda x: f'<img src="{x}" width="80">' if x != "N/A" else "N/A"
)

virginia_wolf.drop(columns=["image_link"], inplace=True)

display(HTML(virginia_wolf.to_html(escape=False)))

## API Wrappers

A Python wrapper is a Python library or module that provides a more convenient or more "Pythonic" interface to another software component, such as a library in another language, a system tool, or a web API. It "wraps" the functionality of that component in a way that abstracts away its complexities and makes it easier to use in a Python context. 🙌🏻

One example is the `tweepy` library, which makes obtaining data from Twitter's API relatively straightforward.

## Summary
- Import the `requests` library.
- Store the necessary credentials, such as API key or OAuth tokens, if the API requires them.
- Execute a `request.get` to the desired API endpoint (the API's documentation will provide details on available endpoints).
- The API returns a JSON response.
- This JSON can be converted into a dataframe, or you can further explore its elements (typically a list of dictionaries).

## Glossary

* DNS: domain name system.
* HTTP: is the protocol used to transfer data over the web.
* API: application programming interface.
* REST: series of rules, architectural style.

* `requests`: Python library for interacting with APIs.
* URL: server name you want to ask information for.
* endpoint: server service you want to ask information for.
* parameters: extra parameters to your query.
* headers: metadata, invisible information.

## Further materials

[5 Simple-To-Use APIs for Beginners](https://dev.to/alanconstantino/5-simple-to-use-apis-for-beginners-2e0n)

[RapidAPI](https://rapidapi.com/category/Sports): access thousands of APIs.